// GÉNÉRÉ par scripts/gen-registry.mjs — NE PAS ÉDITER À LA MAIN.
// Ajouter une entrée = déposer un fichier dans test-scenarios/ puis `npm run gen`.
import type { TestScenario } from './_shared';
import { scenario as e0 } from './13-bataille-de-masse';
import { scenario as e1 } from './14-voyage-maritime';
import { scenario as e2 } from './15-commerce-fluvial';
import { scenario as e3 } from './16-embuscade-fluviale';
import { scenario as e4 } from './17-metamorphose-ulric';
import { scenario as e5 } from './18-effets-scriptes';
import { scenario as e6 } from './19-grimpant';
import { scenario as e7 } from './20-aspersion';
import { scenario as e8 } from './21-chute-du-greement';
import { scenario as e9 } from './42-belier-porte';
import { scenario as e10 } from './43-pastilles-entite';
import { scenario as e11 } from './95-poursuite-terrestre';
import { scenario as e12 } from './96-presets-edo';
import { scenario as e13 } from './97-enquete-carnet';
import { scenario as e14 } from './98-conditions-etendues';
import { scenario as e15 } from './99-revisit';
import { scenario as e16 } from './arene';
import { scenario as e17 } from './bestiaire';
import { scenario as e18 } from './combat-naval';
import { scenario as e19 } from './dialogue-multi';
import { scenario as e20 } from './diligence-salle-pleine';
import { scenario as e21 } from './diligence';
import { scenario as e22 } from './duel-naval';
import { scenario as e23 } from './echeance';
import { scenario as e24 } from './ecuries-clayonnage';
import { scenario as e25 } from './embuscade';
import { scenario as e26 } from './entrainement';
import { scenario as e27 } from './galerie-modeles';
import { scenario as e28 } from './magie-hors-combat';
import { scenario as e29 } from './magie';
import { scenario as e30 } from './marche-equipement';
import { scenario as e31 } from './opera';
import { scenario as e32 } from './piege-caveau';
import { scenario as e33 } from './pont-vitrine';
import { scenario as e34 } from './siege-enceinte';
import { scenario as e35 } from './siege-explore';
import { scenario as e36 } from './voyage';
import { scenario as e37 } from './zones-pieces';

export const SCENARIOS: TestScenario[] = [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35, e36, e37];
