/**
 * SOURCE ASCII du siège — carte ENTIÈRE (sol, rivière+pont, enceinte, chemin de ronde, unités), ÉDITABLE
 * comme un plan. 1 char = 1 case, chaque rangée fait exactement 30 chars. Consommée par `siege-enceinte.ts`.
 *
 * Z0 (sol, base herbe) : '.'=champ · '~'=rivière (eau, infranchissable) · '='=pont (planches) · 'P'=cour (pavé).
 *   La RAMPE d'accès au rempart n'est PAS un terrain particulier : ce sont des cases de cour (P) dont la
 *   HAUTEUR monte ≤1 m/case (posée en code dans `siege-enceinte.ts`) → le moteur fabrique la pente (plus
 *   aucun escalier). Marqueurs : '@'=départ groupe · 'k'=canon de siège ennemi · 'p'=catapulte ennemie
 *   (tir indirect) · 'o'=fantassin ennemi.
 * Z1 (chemin de ronde, base vide) : 'W'=passerelle (pierre, hauteur 4 m posée en code → relief de rempart).
 *   Marqueurs : 'B'=baliste de rempart · 'K'=canon de rempart · 'A'=archer défenseur · 'G'=guetteur
 *   (au-dessus de la porte → chute quand la porte cède).
 *
 * Le chemin de ronde occupe les DEUX cases (y37 côté champ + y38 côté cour) au-dessus de l'arête du mur →
 * rempart ÉPAIS de 2 cases, surplombant le pied du mur. `WALL` décrit l'enceinte (1 char/colonne, arête N
 * de la rangée `WALL_ROW`). PLUS de hauteur sur les `WallSeg` : la verticalité du rempart EST sa hauteur de
 * couche (z1 à 4 m), pas un champ de mur.
 */

export const WALL_ROW = 38;

/** Enceinte (arête N de WALL_ROW) : 'T'=tour · '#'=courtine · 'G'=porte de ville (brèchable) — 'T'/'#'
 *  sont tous des `mur-en-pierre` (plus de distinction de hauteur : la 3ᵉ dimension est la couche z1). */
export const WALL = 'TT##########TTGGTT##########TT';

export const Z0_ASCII = String.raw`
..............................
..............................
........p.....................
..............................
..............................
...............o..............
....o....................o....
..........o........o..........
..............................
..............................
..............................
..............................
..............................
..............................
..............................
.....................k........
..............................
..............................
..............................
..............................
~~~~~~~~~~~~~====~~~~~~~~~~~~~
~~~~~~~~~~~~~====~~~~~~~~~~~~~
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............o...............
..............................
..............................
..............................
..............................
..............................
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
PPPPPPPPPPPPPP@PPPPPPPPPPPPPPP
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
`;

export const Z1_ASCII = String.raw`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
WWWWAWWWWWAWWWGWWWWAWWWWWAWWWW
WWWWWWWWBWWWWWWWWWWWWKWWWWWWWW
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
