/**
 * La Diligence — grille commune 32 × 34, origine nord-ouest.
 * Une case vaut 2 m. Les cases impaires portent le sol, les arêtes paires la structure.
 * Arêtes : `|` / `-` mur, `:` porte, `o` fenêtre, `+` jonction.
 */
export const DILIGENCE_Z0_ASCII = String.raw`
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g g
+ + +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+:+=+=+=+=+=+=+=+=+=+=+=+ + + +
 g g g g g|P P P P|g g g g g g g g g g g g g g g g g g g g g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P|g g g g g g g g g g g g g g g g g g g g g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P|g g g g g g g g g g g g g g g g g g g g g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P|g g g g g g g g g g g g g g g g g g g g g g g
+ + + + + + + + +o+ + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P|g g g g g g g g g g g g g g g g g g g g g g g
+ + + + + +-+-+:+-+ + + + + + + + +:+ + +o+-+-+o+-+-+o+-+-+ + + +
 g g g g g g g:g g C C C C C C|C C C C|C|C C C C P P P P P|g g g
+ + + + + +-+-+o+-+-+-+-+o+-+-+ + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C|C C C C|C:C C C C P P P P Pog g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P C|C C C C C|C C C C|C|C C C C P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + +-+-+-+-+-+-+-+-+-+ + + +
 g g g g g|P P P P C:C C C C C|C C C C|C|C C C C P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C:C C C C:C|C C C C P P P P Pog g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P C|C C C C C|C C C C|C|C C C C P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C|C C C C|C:C C C C P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C|C C C C|C|C C C C P P P P Pog g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P C|C C C C C|C C C C|C|C C C C P P P P P|g g g
+ + + + + +-+-+-+-+-+ + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C|C C C C|C|C C C C P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + +-+-+o+:+-+o+:+-+o+:+ + + +
 g g g g g|P P P P C:C C C C C|C C C C|C C C|C C|P P P|P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P C|C C C C C|C C C C|C C C|C C|P P P|P Pog g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C|C C C C:C C C:C C:P P P:P P|g g g
+ + + + + +-+-+-+-+-+ + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C C C C|C C C C|C C C|C C|P P P|P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + +-+-+:+-+-+ + + +
 g g g g goP P P P C|C C C C C|C C C C|C W C|C C|P P P|P Pog g g
+ + + + + + + + + + + + + + + + + + + + + + +-+-+-+-+-+-+-+ + + +
 g g g g g|P P P P C:C C E C C|C C C C|C W C C C|P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P C|C C E C C|C C C C|C W C C C:P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g goP P P P C|C C E C C|C C C C|C W C C C|P P P P Pog g g
+ + + + + +-+-+o+-+-+-+-+:+o+-+ + + + +-+-+-+-+-+-+-+-+-+-+ + + +
 g g g g g g g g g C C C E C C C C C C C C C C C|P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g g g g g C C C C C C C C C C C C C C C|P P P P Pog g g
+ + + + + +-+-+:+-+-+-+-+-+-+:+-+-+-+-+-+-+:+-+-+ + + + + + + + +
 g g g g g|P P P P P P|P P P P P P P|P P P P P P|P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P P P|P P P P P P P|P P P P P P:P P P P P|g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g:P P P P P P:P P P P P P P:P P P P P P|P P P P Pog g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g g g g|P P P P P P|P P P P P P P|P P P P P P|P P P P P|g g g
+ + + + + +-+-+:+-+-+-+ + + + + + + + + + + + + +-+o+-+:+-+ + + +
 g g J J J|J J J J P P|P P P P P P P|P P P P P P|g g g g g g g g
+ + + + + + + + + + + + + + + + + + +-+-+-+-+-+-+ + + + + + + + +
 g g J J J|J J J J P:P|P P P P P P P|P P P P P P|g g g g g g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
 g g J J J|J J J J P P|P P P P P P P:P P P P P P|g g g g g g g g
+ + + + + +-+o+-+-+o+-+-+-+o+-+-+-+o+-+-+-+o+-+-+ + + + + + + + +
 g g J J J J J J J g g g g g g g g g g g g g g g g g g g g g g g
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
`;

export const DILIGENCE_Z1_ASCII = String.raw`
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + +o+-+-+o+-+-+o+-+ + + + + + + + + + + + +
                        |P P P P P P P P|
+ + + + + +-+-+-+ + + + + + + + + + + + +o+-+-+o+-+-+o+-+-+ + + +
          |P P P|       |P P P P P P P P|P P P P|P P P P P|
+ + + + + + + + + + + + +-+-+:+-+-+-+-+-+ + + + + + + + + + + + +
          oP P P|       |P P P P P P P P|P P P P|P P P P Po
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
          |P P P:       |P P P P P P P P:P P P P:P P P P P|
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
          |P P P|       |P P P P P P P P|P P P P|P P P P P|
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
          oP P P|       |P P P P P P P P|P P P P|P P P P Po
+ + + + + +-+:+-+-+-+-+-+-+-+-+-+-+:+-+-+o+-+:+o+-+-+o+-+-+ + + +
          |P P P|P P P P|P P P P|       |P P P P|P P P P P|
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
          |P P P|P P P P:P P P P|       |P P P P|P P P P Po
+ + + + + + + + + + + + + + +-+-+-+-+-+-+ + + + + + + + + + + + +
          oP P P:P P P P|P P|P P:P P P P:P P P P:P P P P P|
+ + + + + + + + +-+-+-+-+-+-+-+-+ + + + + + + + + + + + + + + + +
          |P P P|P P P P|P P|P P|P P P P|P P P P|P P P P P|
+ + + + + +-+:+-+ + + + + + + + + + + + + + + + + + + + + + + + +
          |P P P|P P P P|P P|P P|P P P P|P P P P|P P P P Po
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
          oP P P|P P P P P P|P P|P P P P|P P P P|P P P P P|
+ + + + + + + + + + + + + + + + + + + +-+-+-+:+-+-+:+-+-+:+ + + +
          |P P P:P P P P P P|P P|P P P|P|P P P P P P P P P|
+ + + + + + + + +-+-+:+-+-+-+-+ + + + + + + + + + + + + + + + + +
          |P P P|P P P P P P|P|P|P P P:P| |P P P|P P|P P Po
+ + + + + +-+:+-+-+-+-+-+-+-+-+-+ + + + + + + + + + + + + + + + +
          |P P P|P P P P   P|P|P P P P|P| :P P P:P P:P P P|
+ + + + + + + + + + + + + + +-+-+:+-+-+-+ + + + + + + + + + + + +
          oP P P|P P P P   P P|       |   |  P P|P P|P P P|
+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
          |P P P:P P P       P|       |   |  P P|P P|P P Po
+ + + + + + + + + + + + + + + + + + + +-+o+-+-+o+-+-+o+-+-+ + + +
          |P P P|P P P       P|
+ + + + + +-+-+o+o+ + + + + + + + + + + + + + + + + + + + + + + +
                |P P P       P|
+ + + + + + + + +-+-+-+-+-+-+o+ + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

+ + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
`;

export const DILIGENCE_Z0_ZONES = String.raw`
................................
....MAAAACCCCCCCCCCCCCCCCCCCC...
.....AAAACCCCCCCCCCCCCCCCCCCC...
.....AAAACCCCCCCCCCCCCCCCCCCC...
.....AAAACCCCCCCCCCCCCCCCCCCC...
.....AAAACCCCCCCCCCCCCCCCCCCC...
...............VVVV.RRRRRRRRR...
.....KKKKKSSSSSVVVV.RRRRRRRRR...
.....KKKKKSSSSSVVVV.RRRRRRRRR...
.....KKKKKSSSSSVVVV.UUUUUUUUU...
.....KKKKKSSSSSVVVV.UUUUUUUUU...
.....KKKKKSSSSSVVVV.UUUUUUUUU...
.....KKKKKSSSSSVVVV.UUUUUUUUU...
.....KKKKKSSSSSVVVV.UUUUUUUUU...
.....KKKKKSSSSSVVVV.UUUUUUUUU...
.....LLLLLSSSSSVVVV.UUUUUUUUU...
.....LLLLLSSSSSVVVV...HHIIIjj...
.....LLLLLSSSSSVVVV...HHIIIjj...
.....LLLLLSSSSSVVVV...HHIIIjj...
.....PPPPPSSSSSVVVV...HHIIIjj...
.....PPPPPSSSSSZZZZZZZHHIIIjj...
.....PPPPPSSSSSZZZZZZZZZBBBBB...
.....PPPPPSSSSSZZZZZZZZZBBBBB...
.....PPPPPSSSSSZZZZZZZZZBBBBB...
.........ZZZZZZZZZZZZZZZBBBBB...
.........ZZZZZZZZZZZZZZZBBBBB...
.....FFFFFFEEEEEEEeeeeeeBBBBB...
.....FFFFFFEEEEEEEeeeeeeBBBBB...
.....FFFFFFEEEEEEEeeeeeeBBBBB...
.....FFFFFFEEEEEEEeeeeeeBBBBB...
..JJJrrrrrrEEEEEEEeeeeee........
..JJJrrrrrrEEEEEEE..............
..JJJrrrrrrEEEEEEE..............
..JJJ...........................
`;

export const DILIGENCE_Z1_ZONES = String.raw`
................................
................................
................................
................................
................................
................................
................................
............nnnnnnnn............
.....YYY....nnnnnnnnTTTTttttt...
.....YYY....GGGGGGGGTTTTttttt...
.....YYY....GGGGGGGGTTTTttttt...
.....YYY....GGGGGGGGTTTTttttt...
.....YYY....GGGGGGGGTTTTttttt...
.....QQQllllrrrrXXXXDDDDddddd...
.....QQQllllrrrrXXXXDDDDddddd...
.....QQQllllrrrrXXXXDDDDddddd...
.....QQQXXXXXXggggggDDDDddddd...
.....qqqXXXXXXggggggDDDDddddd...
.....qqqXXXXXXggggggDDDDddddd...
.....qqqXXXXXXgggggOOOOOOOOOO...
.....NNNXXXXXXgggggO.aaabbccc...
.....NNNXXXX.XgggggO.aaabbccc...
.....NNNXXXX.XXXXXX...aabbccc...
.....NNNXXX...XXXXX...aabbccc...
.....NNNXXX...XXXXX.............
........XXX...XXXXXX............
................................
................................
................................
................................
................................
................................
................................
................................
`;
