import type { Roof, Scene } from '../../state/scene';
import { buildScene, type MapSpec } from '../../state/mapSpec';
import { DILIGENCE_FLOORPLAN_SPEC } from './floorplan';

const DILIGENCE_Z0_FURNITURE = String.raw`
................................
................................
................................
......d.........................
................................
................................
................................
.....................s.bs..s....
......m.......m......n....n.....
.......p........................
.......T...cTc..................
.........k...........cTc........
.........................cTc....
........s.......................
...........cTc..................
................................
................................
......................l.l..l....
...........cTc..................
.......................x.x..x...
.........m......................
.......d........................
........x...................b...
.........................u......
................................
...........................ub...
................................
......f.a...i.i.i..i.....u......
.........w..................b...
...................q............
.............h.h....h...........
......sbs...v...................
......n..n......................
................................
`;

const DILIGENCE_Z1_FURNITURE = String.raw`
................................
................................
................................
................................
................................
................................
................................
............R..R.R..............
................................
.....L...............L...L......
......D......D..................
.......X......BAB......X...X....
................................
.....X..........................
.....L....S..SNN.R...L...L......
................................
................................
................D......X...X....
.....L.........BABB.............
....X..........D................
.....................L..L.L.....
........R........R..............
......................X..X..X...
................................
........R.......................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

const BIND: NonNullable<MapSpec['bind']> = {
  T: { kind: 'prop', ref: 'table' },
  c: { kind: 'prop', ref: 'chaise' },
  m: { kind: 'prop', ref: 'cheminee' },
  p: { kind: 'prop', ref: 'marmite' },
  s: { kind: 'prop', ref: 'etagere' },
  k: { kind: 'prop', ref: 'comptoir' },
  f: { kind: 'prop', ref: 'foyer-de-forge' },
  a: { kind: 'prop', ref: 'enclume' },
  w: { kind: 'prop', ref: 'etabli' },
  u: { kind: 'prop', ref: 'cuve-brasserie' },
  b: { kind: 'prop', ref: 'tonneau' },
  i: { kind: 'prop', ref: 'stalle-ecurie' },
  h: { kind: 'prop', ref: 'tas-foin' },
  v: { kind: 'prop', ref: 'abreuvoir', foot: { w: 2, h: 1 } },
  q: { kind: 'prop', ref: 'charrette', foot: { w: 2, h: 1 } },
  n: { kind: 'prop', ref: 'caisse' },
  l: { kind: 'prop', ref: 'lit', foot: { w: 2, h: 1 } },
  x: { kind: 'prop', ref: 'coffre' },
  d: { kind: 'prop', ref: 'bureau' },
  L: { kind: 'prop', ref: 'lit', foot: { w: 2, h: 1 }, z: 1 },
  X: { kind: 'prop', ref: 'coffre', z: 1 },
  D: { kind: 'prop', ref: 'bureau', z: 1 },
  A: { kind: 'prop', ref: 'table', z: 1 },
  B: { kind: 'prop', ref: 'chaise', z: 1 },
  S: { kind: 'prop', ref: 'etagere', z: 1 },
  N: { kind: 'prop', ref: 'caisse', z: 1 },
  R: { kind: 'prop', ref: 'balustrade-bois', foot: { w: 3, h: 1 }, z: 1 },
};

const MARKER_FILL = Object.fromEntries(Object.keys(BIND).map((char) => [char, 'g']));

const roof = (id: string, z: number, x: number, y: number, w: number, h: number): Roof => ({
  id,
  z,
  foot: { x, y, w, h },
  style: 'maison',
  params: { roofMaterial: 'tuile' },
});

const DILIGENCE_ROOFS: Roof[] = [
  roof('diligence-z0-portier', 0, 5, 1, 4, 5),
  roof('diligence-z0-passage-nord', 0, 15, 6, 4, 1),
  roof('diligence-z0-aile-est', 0, 20, 6, 9, 10),
  roof('diligence-z0-aile-ouest', 0, 5, 7, 14, 13),
  roof('diligence-z0-chambres-est', 0, 22, 16, 7, 5),
  roof('diligence-z0-salon-salle', 0, 5, 20, 10, 4),
  roof('diligence-z0-brasserie', 0, 24, 21, 5, 5),
  roof('diligence-z0-aile-sud', 0, 5, 26, 24, 4),
  roof('diligence-z0-sud-centre', 0, 5, 30, 19, 1),
  roof('diligence-z0-sud-ouest', 0, 5, 31, 13, 2),
  roof('diligence-z1-chambre-gustav', 1, 5, 8, 3, 5),
  roof('diligence-z1-nord-est', 1, 20, 8, 9, 1),
  roof('diligence-z1-aile-nord', 1, 12, 9, 17, 4),
  roof('diligence-z1-aile-centre', 1, 5, 13, 24, 7),
  roof('diligence-z1-galerie-ouest', 1, 8, 20, 12, 1),
  roof('diligence-z1-chambres-est', 1, 21, 20, 8, 2),
  roof('diligence-z1-galerie-sud-ouest', 1, 8, 21, 4, 2),
  roof('diligence-z1-galerie-sud-centre', 1, 13, 21, 7, 1),
  roof('diligence-z1-couloir-sud', 1, 13, 22, 6, 1),
  roof('diligence-z1-chambres-sud-est', 1, 22, 22, 7, 2),
  roof('diligence-z1-tour-sud-ouest', 1, 8, 23, 3, 3),
  roof('diligence-z1-galerie-basse', 1, 14, 23, 5, 2),
  roof('diligence-z1-galerie-pointe', 1, 14, 25, 6, 1),
];

export function buildDiligenceScene(): Scene {
  const scene = buildScene({
    ...DILIGENCE_FLOORPLAN_SPEC,
    levels: {
      z0: DILIGENCE_Z0_FURNITURE,
      z1: DILIGENCE_Z1_FURNITURE,
    },
    bind: BIND,
    markerFill: MARKER_FILL,
  });
  return {
    ...scene,
    roofs: DILIGENCE_ROOFS.map((entry) => ({
      ...entry,
      foot: { ...entry.foot },
      params: entry.params ? { ...entry.params } : undefined,
    })),
  };
}
