// ⚠️ GÉNÉRÉ par scripts/gen-registry.mjs — NE PAS ÉDITER À LA MAIN.
// Ajouter une entrée = déposer un fichier dans defs/ puis `npm run gen`.
import type { WeaponDef } from './types';
import { weapon as e0 } from './defs/arbalete';
import { weapon as e1 } from './defs/arbalete_lourde';
import { weapon as e2 } from './defs/arbalete_poing';
import { weapon as e3 } from './defs/arc';
import { weapon as e4 } from './defs/arc_court';
import { weapon as e5 } from './defs/arc_elfique';
import { weapon as e6 } from './defs/arc_long';
import { weapon as e7 } from './defs/arquebus_rep';
import { weapon as e8 } from './defs/arquebuse';
import { weapon as e9 } from './defs/baton';
import { weapon as e10 } from './defs/bec_de_corbin';
import { weapon as e11 } from './defs/bolas';
import { weapon as e12 } from './defs/bombe';
import { weapon as e13 } from './defs/bombe_incendiaire';
import { weapon as e14 } from './defs/brise_epee';
import { weapon as e15 } from './defs/couteau';
import { weapon as e16 } from './defs/couteau_lancer';
import { weapon as e17 } from './defs/dague';
import { weapon as e18 } from './defs/epee_batarde';
import { weapon as e19 } from './defs/fleau';
import { weapon as e20 } from './defs/fleau_armes';
import { weapon as e21 } from './defs/fleau_grain';
import { weapon as e22 } from './defs/flechette';
import { weapon as e23 } from './defs/fleuret';
import { weapon as e24 } from './defs/fouet';
import { weapon as e25 } from './defs/fronde';
import { weapon as e26 } from './defs/fustibale';
import { weapon as e27 } from './defs/gourdin';
import { weapon as e28 } from './defs/grande_hache';
import { weapon as e29 } from './defs/hache_lancer';
import { weapon as e30 } from './defs/hallebarde';
import { weapon as e31 } from './defs/hochland';
import { weapon as e32 } from './defs/improvisee';
import { weapon as e33 } from './defs/javelot';
import { weapon as e34 } from './defs/lance';
import { weapon as e35 } from './defs/lance_cavalerie';
import { weapon as e36 } from './defs/lasso';
import { weapon as e37 } from './defs/main_gauche';
import { weapon as e38 } from './defs/marteau_guerre';
import { weapon as e39 } from './defs/pioche_2m';
import { weapon as e40 } from './defs/pique';
import { weapon as e41 } from './defs/pistolet';
import { weapon as e42 } from './defs/pistolet_rep';
import { weapon as e43 } from './defs/poing';
import { weapon as e44 } from './defs/rapiere';
import { weapon as e45 } from './defs/rocher';
import { weapon as e46 } from './defs/tromblon';
import { weapon as e47 } from './defs/zweihander';

export const WEAPON_DEFS: WeaponDef[] = [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35, e36, e37, e38, e39, e40, e41, e42, e43, e44, e45, e46, e47];
