// ⚠️ GÉNÉRÉ par scripts/gen-registry.mjs — NE PAS ÉDITER À LA MAIN.
// Ajouter une entrée = déposer un fichier dans defs/ puis `npm run gen`.
import type { TraitDef } from './types';
import { trait as e0 } from './defs/a-sang-froid';
import { trait as e1 } from './defs/affame';
import { trait as e2 } from './defs/belliqueux';
import { trait as e3 } from './defs/bestial';
import { trait as e4 } from './defs/bond';
import { trait as e5 } from './defs/brutal';
import { trait as e6 } from './defs/champion';
import { trait as e7 } from './defs/coriace';
import { trait as e8 } from './defs/corruption-mentale';
import { trait as e9 } from './defs/demoniaque';
import { trait as e10 } from './defs/elite';
import { trait as e11 } from './defs/endurant';
import { trait as e12 } from './defs/ethere';
import { trait as e13 } from './defs/fabrique';
import { trait as e14 } from './defs/foulee';
import { trait as e15 } from './defs/furtif';
import { trait as e16 } from './defs/grand';
import { trait as e17 } from './defs/immunite';
import { trait as e18 } from './defs/infravision';
import { trait as e19 } from './defs/insensible-a-la-douleur';
import { trait as e20 } from './defs/instable';
import { trait as e21 } from './defs/intelligent';
import { trait as e22 } from './defs/magique';
import { trait as e23 } from './defs/meneur';
import { trait as e24 } from './defs/mutation';
import { trait as e25 } from './defs/nerveux';
import { trait as e26 } from './defs/parasite';
import { trait as e27 } from './defs/perturbant';
import { trait as e28 } from './defs/protection';
import { trait as e29 } from './defs/rage';
import { trait as e30 } from './defs/rapide-trait';
import { trait as e31 } from './defs/regeneration';
import { trait as e32 } from './defs/resistance-a-la-magie';
import { trait as e33 } from './defs/ruse';
import { trait as e34 } from './defs/sang-corrosif';
import { trait as e35 } from './defs/stupide';
import { trait as e36 } from './defs/territorial';
import { trait as e37 } from './defs/toile';
import { trait as e38 } from './defs/vision-nocturne';
import { trait as e39 } from './defs/vol';

export const TRAIT_DEFS: TraitDef[] = [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35, e36, e37, e38, e39];
