// Stock NOMINATIF DATÉ des sites de la famille (e) du garde-fou commentaires — #1486, credo règle 1.
// Mécanique du scan : `scanLegacyVocab` (`scripts/guards/lib/commentPoison.mjs`) ; verdict et cliquet :
// `src/comment-poison-guard.test.ts`. Ici ne vit QUE la donnée.
//
// Un site se nomme par FICHIER + ANCRE de texte + MOTIF (jamais un numéro de ligne, qui dérive au
// premier commit voisin) : un commentaire qui porte DEUX motifs compte pour DEUX lignes, et falsifier
// le motif d'une ligne la fait sortir du stock. `lot` = le chantier qui l'éteint, pris dans l'ensemble
// FERMÉ des lots de #1486 (validé par le test) ; `date` = la mesure d'origine. Contrat BIDIRECTIONNEL
// tenu par le test : un site du dépôt absent d'ici est ROUGE, une entrée d'ici qui ne matche plus rien
// est ROUGE (elle se purge). Cette liste DÉCROÎT jusqu'à 0 : chaque lot part avec ses lignes. Une ligne
// y entre par la seule EXTENSION DE COUVERTURE du détecteur, mesurée et datée dans le commit qui étend
// la famille (lot `L7`, 2026-09-26, #1486 #1509) ; un site neuf se corrige au geste.
//
// Périmètre : `src/**` + `scripts/**` (`.ts`, `.tsx`, `.mts`, `.mjs`, tests compris). Mesures :
// 2026-08-23 ; 2026-09-26 (lot `L7`).

/**
 * @typedef {{ fichier: string, motif: string, ancre: string, lot: string, date: string }} SiteVocab
 */

/** @type {SiteVocab[]} */
export const LEGACY_VOCAB_SITES = [
  {
    fichier: "scripts/data/html-to-md.mjs",
    motif: "legacy",
    ancre: "(`src/data/*.json`) qui contient encore du HTML (legacy : `<br><br>`, `<b>`, `<i>`, `<ul><li>`…).",
    lot: "L1b #1467",
    date: "2026-08-23",
  },
  {
    fichier: "scripts/data/html-to-md.mjs",
    motif: "legacy",
    ancre: "// `<br>` legacy = séparateur de paragraphe (turndown collapse les `\\n` adjacents → un `<br>` simple",
    lot: "L1b #1467",
    date: "2026-08-23",
  },
  {
    fichier: "src/engine/ops.ts",
    motif: "rétro-compat",
    ancre: "jamais forcé), borné à `overcastDurationSteps`. Absent = tous les pas alloués (défaut, IA/rétrocompat). */",
    lot: "L1c #1468",
    date: "2026-08-23",
  },
  {
    fichier: "src/engine/provisions.ts",
    motif: "rétro-compat",
    ancre: "de cale (le port avitaille les deux). Absent = seuls les héros comptent (rétro-compat). */",
    lot: "L4",
    date: "2026-08-23",
  },
  {
    fichier: "src/engine/trauma.ts",
    motif: "legacy",
    ancre: "Omis (tests/legacy) ⇒ pas de décompte (séquelle permanente jusqu'à traitement explicite). */",
    lot: "L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/engine/trauma.ts",
    motif: "obsolète",
    ancre: "obsolète, elle, est refusée à la lecture) — sortirait sinon de la somme additive pour le pool",
    lot: "L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/engine/types.ts",
    motif: "legacy",
    ancre: "à 0 le trauma (et ses pénalités) disparaît. Absent = trauma legacy/permanent (pas de décompte). */",
    lot: "L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/builders/types.ts",
    motif: "legacy",
    ancre: "/** Relations stables d'une façade architecturale authorée. Absentes sur les murs legacy. */",
    lot: "L1b #1467",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/bodyPlan.ts",
    motif: "legacy",
    ancre: "déclare son `id`). Le monolithique n'est PAS un BodyPlan (fallback legacy hors registre). */",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/derive.ts",
    motif: "shim",
    ancre: "tenue sans art dédié. Un def qui déclare ses vraies vues les garde (le shim ne dérive que l'absent).",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/derive.ts",
    motif: "shim",
    ancre: "FRONT (cf. `dominantCloth`). Une tenue qui fournit `profile` prime (le shim ne dérive que l'absent).",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/derive.ts",
    motif: "legacy",
    ancre: "matérialisé dans un def qui déclare ses vues, appelé par le shim `toViewSet` pour l'art legacy. */",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/derive.ts",
    motif: "shim",
    ancre: "matérialisé dans un def qui déclare ses vues, appelé par le shim `toViewSet` pour l'art legacy. */",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/derive.ts",
    motif: "legacy",
    ancre: "`PartArt` legacy (string front-only, ou objet à vues partielles). `toViewSet` l'enrobe en `ViewSet`",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/derive.ts",
    motif: "shim",
    ancre: "// SHIM P1 (retiré P3) : les registres de corps (tenue/armure/générique/override) stockent encore un",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/resolve.ts",
    motif: "legacy",
    ancre: "legacy, ENROBÉ en `ViewSet` TOTAL par le shim `toViewSet` (P1), qui matérialise les vues absentes",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/resolve.ts",
    motif: "shim",
    ancre: "legacy, ENROBÉ en `ViewSet` TOTAL par le shim `toViewSet` (P1), qui matérialise les vues absentes",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/types.ts",
    motif: "shim",
    ancre: "une vue manquante est une erreur de compile). Produit à l'ingestion par le shim `toViewSet`",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/rig/parts/types.ts",
    motif: "shim",
    ancre: "`string` = front-only (le shim `toViewSet` DÉRIVE alors la vue absente). Consommé par la garde de",
    lot: "chantier rig",
    date: "2026-08-23",
  },
  {
    fichier: "src/gameIso/stage/GameStage3D.tsx",
    motif: "déprécié",
    ancre: "// `PCFSoftShadowMap` est DÉPRÉCIÉ depuis three 0.185 : le moteur le remplace lui-même par",
    lot: "lot rendu",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/combatEndBands.ts",
    motif: "legacy",
    ancre: "tient les étapes LEGACY d'une sauvegarde, qui ne portent aucun discriminant d'entrée.",
    lot: "L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/combatEndBands.ts",
    motif: "legacy",
    ancre: "Degré d'exposition à la Corruption. Une étape LEGACY (sauvegarde d'avant L4) n'a pas d'`entry` :",
    lot: "L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/combatFlow.ts",
    motif: "rétro-compat",
    ancre: "(un fallback id→libellé = rétro-compatibilité, proscrite). Les libellés restent au seul niveau AUTHORING. */",
    lot: "L1c #1468 / #1474",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/combatFlow.ts",
    motif: "rétro-compat",
    ancre: "`target` (optionnel — rétro-compat) sert le combat « au contact » (LDB 62 l.176) : une arme plus longue",
    lot: "#1474",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/combatFlow.ts",
    motif: "rétro-compat",
    ancre: "DÉCLINABLE (l.276 « vous pouvez ») : `chosenTableRolls` (absent = tous les pas, IA/rétrocompat).",
    lot: "L1c #1468",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/projectLibrary.ts",
    motif: "legacy",
    ancre: "de projet, jamais un littéral `schema`/champs dupliqués), mais RELÂCHÉE pour le stock legacy : un",
    lot: "L1b #1467",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/saves.ts",
    motif: "legacy",
    ancre: "SEULE dans le contenu (`SaveGame.version`). `LEGACY_KEY` sert seulement à NETTOYER les clés",
    lot: "L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/data/schemas/defs-scenes/effets.ts",
    motif: "legacy",
    ancre: "= ½ prix mais nourriture à risque (Courante galopante 10 %, ch.66 l.51). LEGACY : sans",
    lot: "L1b #1467 / L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/shipwreck.ts",
    motif: "legacy",
    ancre: "MDG 13 l.674 « corps et biens ») ; sans correspondance, la purge legacy `vessel:null` ci-dessus reste",
    lot: "L1b #1467 / L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/state/store.ts",
    motif: "legacy",
    ancre: "les scènes + re-dérive `campaignNarratif` au chargement d'une save. null = chemin Arène / save legacy. */",
    lot: "L1b #1467 / L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/ui/editor/Editor.tsx",
    motif: "legacy",
    ancre: "/** Identité de campagne (#765/#766) — préservée au round-trip, absente d'un projet legacy sans identité. */",
    lot: "L1b #1467 / L5",
    date: "2026-08-23",
  },
  {
    fichier: "src/ui/HeroSheet.tsx",
    motif: "rétro-compat",
    ancre: "/** Champs de la rubrique `derived` — TOUS par défaut (rétro-compatible). Un appelant qui porte déjà",
    lot: "L6",
    date: "2026-08-23",
  },
  {
    fichier: "src/ui/HeroSheet.tsx",
    motif: "rétro-compat",
    ancre: "/** Rubriques rendues — TOUTES par défaut (rétro-compatible). Un appelant qui porte déjà une partie",
    lot: "L6",
    date: "2026-08-23",
  },
  {
    fichier: "src/data/aa-base-weapons.test.ts",
    motif: "désormais",
    ancre: "Cimeterre/Dague ballock (#563 Lot 2) : l'ancre porte désormais le folio de la PROSE (90, règle 5),",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/actions-cout-maison.test.ts",
    motif: "désormais",
    ancre: "mort — ce que le TYPE garde désormais se mesure ici, sur la donnée réelle mutée, sans quoi la mort",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/career-progression-gap.test.ts",
    motif: "désormais",
    ancre: "Ticket #883 : la ligne de NIVEAU 1 est désormais lisible pour les 10 carrières via `pdfminer.six`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/champs-declares-parite.test.ts",
    motif: "désormais",
    ancre: "(`t.id === 'arme'`, `t.id !== 'bestial'`, `builtinId === 'mains-nues'`…). Ils vivent désormais sur",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/champs-declares-parite.test.ts",
    motif: "désormais",
    ancre: "désormais DÉCLARÉ sur l'entrée marqueur, lu par `isTradeHubEntry` (`engine/cargo.ts`).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/dataset-id-parity.test.ts",
    motif: "désormais",
    ancre: "désormais un champ `id` STABLE en donnée. Deux invariants, la classe est fermée :",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/domains-wind-schema.test.ts",
    motif: "désormais",
    ancre: "exige désormais une provenance par entrée, et ces 7 fixtures rejouent des Domaines RÉELS. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/index-vif-guard.test.ts",
    motif: "désormais",
    ancre: "SONT désormais du VOCABULAIRE, joués à ce lot (les deux formes par lesquelles le module",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/index-vif-guard.test.ts",
    motif: "désormais",
    ancre: "// Et le détecteur VOIT désormais un index figé sur ce nom, injecté dans une copie en mémoire.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/libelles-guard.test.ts",
    motif: "désormais",
    ancre: "montrait son trou nommé entre accolades, il le DIT désormais en français (`defs/voyage-stakes.ts`).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/maison-sans-source.test.ts",
    motif: "désormais",
    ancre: "désormais `maison`. Ce n'est pas une dérive, c'est un angle mort qui devient un compte. Les axes",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/maison-sans-source.test.ts",
    motif: "désormais",
    ancre: "sont désormais écrites (`scripts/migrations/2026-09-02-1680-props-provenance.mjs`) et EXIGÉES par",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/migrations-type-enveloppe.test.ts",
    motif: "désormais",
    ancre: "ressuscité (« arbitrage requis » sur toutes les entrées, rejeu ROUGE). Ils distinguent désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/obtainability-guard.test.ts",
    motif: "désormais",
    ancre: "`grantTalent`) → 8 → 1. Le graphe lit désormais `tables.json` comme source d'octroi",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/prop-foot-migration.test.ts",
    motif: "désormais",
    ancre: "// `balustrade-loge` se pose désormais à la CASE (une travée par case de rive de puits,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/prop-foot-migration.test.ts",
    motif: "désormais",
    ancre: "désormais 1×1 pour les trois tables d'Opéra, et ce contrat prouverait l'inverse de son titre. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/prose-resolution.test.ts",
    motif: "désormais",
    ancre: "entrer est désormais FERMÉE PAR LA LIB : une cellule résolue rend le saut de ligne IMPRIMÉ",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/refs-migrated.test.ts",
    motif: "désormais",
    ancre: "Un Test déclenché authoré est désormais un nœud de STRUCTURE Flow (`{kind:'test', test:FlowTest}`) ;",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/refs-migrated.test.ts",
    motif: "désormais",
    ancre: "4bis de L2 #1548 : ces lignes portent désormais `choix: [ids]`, que la marche ci-dessus rend au",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/refs-migrated.test.ts",
    motif: "désormais",
    ancre: "`trappingRefLabel` affiche désormais la `spec` (par `refConcrete`), ce qui lève la réserve notée",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/regles-optionnelles-partition.test.ts",
    motif: "désormais",
    ancre: "// 2 → 24 (#1688) : les 24 Structures citent leur folio (ADE II 89, AA 119-120) ET portent désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schema-contract.test.ts",
    motif: "désormais",
    ancre: "(c) CLIQUET : une entrée `PENDING` qui a désormais un schéma doit en SORTIR (sinon la liste ne",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/defs-scenes/effets.test.ts",
    motif: "désormais",
    ancre: "3. L'ÉQUIVALENCE DE TYPE. `Effect` est désormais COMPOSÉ des infers ; rien n'empêche un infer de",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/document.ts",
    motif: "désormais",
    ancre: "CONSOMME désormais `entreePartielle`. Sur le nœud SCELLÉ, `.partial` n'existe pas et l'appel",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/document.ts",
    motif: "désormais",
    ancre: "variantes lisent désormais `cles` — plus aucun `element.shape`, le dernier est mort avec",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/grammaire.test.ts",
    motif: "désormais",
    ancre: "désormais au def, et le verrou d'exigence ci-dessous le prouve entrée par entrée.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/reference.ts",
    motif: "désormais",
    ancre: "seconde graphie de la même chose, que rien ne lisait — elle est désormais REFUSÉE au parse. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/sans-livre.ts",
    motif: "désormais",
    ancre: "désormais `maison`. Mesuré le 2026-09-05 (après la fusion des trois catalogues de matières en",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/slots.test.ts",
    motif: "désormais",
    ancre: "son def — la Compétence testée par une rangée de Critique est désormais celle du nœud",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/schemas/grammaire/valeurs.ts",
    motif: "désormais",
    ancre: "une GARDE la lit désormais : quand elle est de la forme `<ABRÉV> <ch> l.<ligne>`,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/slots-contrat.test.ts",
    motif: "désormais",
    ancre: "valeur « montagnes » résolvant désormais vers la spécialisation `bon-marcheur/montagnes` ajoutée au",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/slots-contrat.test.ts",
    motif: "désormais",
    ancre: "d’un symptôme porte désormais sa conséquence sous la feuille `EffectOp` du nœud `test`, et ses deux",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/stake-rule-ratchet.test.ts",
    motif: "désormais",
    ancre: "fiche curée pour un jet DOIT désormais être référencée par un dataset d'enjeu. Une fiche qui",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/variants-integrity.test.ts",
    motif: "désormais",
    ancre: "désormais adoptés : aucun ne se lit plus au nœud zod. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/data/zde-affects-authoring.test.ts",
    motif: "désormais",
    ancre: "`affects` décide désormais. Portée : le camp du candidat (toute mention d'alliance) et les deux",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/buildWeapon.test.ts",
    motif: "désormais",
    ancre: "quelle (jamais une chaîne re-parsée). Le token `BF` est désormais porté par le flag `plusBF` (lu par",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/combat-breakdown.test.ts",
    motif: "désormais",
    ancre: "partait en chip « autres ». La Difficulté est désormais COMPOSÉE une fois par qui roule le jet, puis",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/combat.ts",
    motif: "désormais",
    ancre: "*Groupées* — chaque Spécialisation (désormais un `spec` = id de Groupe, cf. `SkillData.specsSource`)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/combat.ts",
    motif: "désormais",
    ancre: "10 (l.282). L'OVERKILL (Blessures perdues > PB COURANTS, LDB 18 l.17) est désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/combatFeatures/types.ts",
    motif: "désormais",
    ancre: "(Le +DR de Talent — Menaçant → Intimidation — est désormais la règle UNIVERSELLE `talentTestSLBonus`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/corruption.ts",
    motif: "désormais",
    ancre: "sont désormais émis par le collecteur passif unifié (`passiveSkillSum`/`passiveTestMod`, engine/trauma).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/creation.test.ts",
    motif: "désormais",
    ancre: "// Le filtre historique masquait TOUT le livre NADJ ; il porte désormais sur le champ déclaré par",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/crewedWeapon.ts",
    motif: "désormais",
    ancre: "RETIRE la qualité `arme-d-equipe` — l'équipage RÉEL étant désormais résolu, l'hypothèse « maniée en solo »",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/crit-rng-invariance.test.ts",
    motif: "désormais",
    ancre: "rougisse : le compte est désormais ÉCRIT ici, pas seulement encodé dans la fixture.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/critical.test.ts",
    motif: "désormais",
    ancre: "est désormais tiré par l'op, à l'application — c'est une QUANTITÉ, pas un Test.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/death.test.ts",
    motif: "désormais",
    ancre: "// la finalisation est désormais portée par le store",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/disease-noeud-test.test.ts",
    motif: "désormais",
    ancre: "cas prouve est la COUVERTURE, et elle est désormais ASSERTÉE à partir de la DONNÉE (tout porteur",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/effect-rule-anchor.test.ts",
    motif: "désormais",
    ancre: "talents, qualités, symptômes, États, psychologie, via `effectSourcesOf` — sont désormais ancrés). La",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/engine.test.ts",
    motif: "désormais",
    ancre: "// Dégâts de poison désormais data-driven (etats.json + fireConditionEffects, cf. state/etat-perround.test) :",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/engine.test.ts",
    motif: "désormais",
    ancre: "// dégâts de feu désormais data-driven (cf. state/etat-perround.test)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/exposure-heat-sealskin.test.ts",
    motif: "désormais",
    ancre: "d'`engine/exposure` sert désormais les deux volets (Température en mer, MDG 13 l.203-225).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/groups-portage-1357.test.ts",
    motif: "désormais",
    ancre: "(`FOLDER_RULES`) et par TABLE DE TRAIT (`TRAIT_RULES`) est morte — les Groupes sont désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/magic.ts",
    motif: "désormais",
    ancre: "Arcanes portent désormais des IDS de domaine (fin de l'incohérence Vent/Lore) → ils matchent. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/menace.test.ts",
    motif: "désormais",
    ancre: "// La spec du talent ET le tag `menace` sont désormais TOUS DEUX des ids stables ('maladie') —",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/opposed-base-explicite.test.ts",
    motif: "désormais",
    ancre: "Contrat désormais tenu par construction :",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/ops.ts",
    motif: "désormais",
    ancre: "inline — les Tests imbriqués des tables d'Imparfaites/Colère, LDB 46/40 — sont désormais des nœuds",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/overcast.test.ts",
    motif: "désormais",
    ancre: "TABLEAU DE SURINCANTATION (`VDM 02 l.207-215`), désormais en DONNÉE (`src/data/surincantation.json`,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/prix-offre-bandes.test.ts",
    motif: "désormais",
    ancre: "Ils sont désormais des fourchettes `{min, max}` lues par `findTableEntry` (`./tables`), la dernière",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/prix-offre-bandes.test.ts",
    motif: "désormais",
    ancre: "tableau s'arrêtant à 5 (l.52-60), un indice 6 est désormais REFUSÉ et NOMMÉ.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/provisions.test.ts",
    motif: "désormais",
    ancre: "« toutes les autres » désormais touchées",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/seaVoyage.ts",
    motif: "désormais",
    ancre: "// La cargaison EMBARQUÉE (CargoLot, cargoTotalEnc, removeCargo) est désormais le tronc commun de",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/spellDuration.ts",
    motif: "désormais",
    ancre: "Replie l'ancien champ structuré `durationRounds: Formula` (échelle tactique) — source UNIQUE désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/spellspec.test.ts",
    motif: "désormais",
    ancre: "résolue contre le lanceur). La durée et les effets vivent désormais sur SpellData (données JSON). */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/spellspec.ts",
    motif: "désormais",
    ancre: "désormais comme des ops (non-`narrative`) → comptées mécaniques par le filtre ci-dessous ; restent ici",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/talentEffects.ts",
    motif: "désormais",
    ancre: "incluant les +5 de talent (désormais passifs, plus cuits dans `characteristics`).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/talentEffects.ts",
    motif: "désormais",
    ancre: "Le +5 Caractéristique et le +1 Mouvement sont désormais des PASSIFS CONTINUS dans `passive: GameOp[]`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/traits/dispatch.ts",
    motif: "désormais",
    ancre: "sont désormais des traits EN DONNÉE : plus aucune liste de libellés en dur à tenir alignée. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/traits/parity.test.ts",
    motif: "désormais",
    ancre: "Parité des Traits de créature (LDB 85). Le registre `TRAITS` est désormais DÉRIVÉ 1:1 de la donnée",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/trauma.ts",
    motif: "désormais",
    ancre: "portée par la fiche (déchirures ET fractures sont désormais des fiches par localisation+sévérité).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/trauma.ts",
    motif: "désormais",
    ancre: "canal `charMod` dit désormais la MÊME chose que le canal `skillMod`, #1153). `ref` accompagne le nom",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/engine/types.ts",
    motif: "désormais",
    ancre: "/** (Détermination : l'immunité psy temporaire + l'ignorance des modifs de Critique sont désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/authoring/wallsSvg.ts",
    motif: "désormais",
    ancre: "depuis la palette unifiée du JSON) est désormais ombrée comme le bois : sa face N recule dans l'ombre,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/backends/webgl/monte-composite.test.tsx",
    motif: "désormais",
    ancre: "C5a — il mesure désormais le MÊME canal sur le sujet volumique, seul rendu du couple.)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/backends/webgl/sceneCutaway.test.ts",
    motif: "désormais",
    ancre: "des faces par groupe. Elle ignore les POSITIONS — le rang coplanaire se calcule désormais sur la",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/backends/webgl/spriteRaycast.ts",
    motif: "désormais",
    ancre: "jeton occulté est désormais son corps entier, à la boîte près : sa surface de réponse au clic est",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/builders/propVolumes.test.ts",
    motif: "désormais",
    ancre: "// Le cap `N` est désormais le DEMI-TOUR : le pied et le rampant changent de bord.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/catalog/structures/index.ts",
    motif: "désormais",
    ancre: "5 px de trait à 2 m/tuile), désormais authorées en mètres. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/anim/creatureAttackPoses.ts",
    motif: "désormais",
    ancre: "le cou (haut-arrière), POSITIF le plonge en avant ; la queue `reptile` TRAÎNE désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/composeRig.tsx",
    motif: "désormais",
    ancre: "trou nul. La main passe juste SOUS l'os d'AVANT-BRAS (#633 D1 : c'est lui qui porte désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/creatures/defs/Boeuf.ts",
    motif: "désormais",
    ancre: "// FACE : le poitrail est désormais LARGE au socle (`bodyWidth.front = 22`, déclaré par la def de",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/enemyProfile.test.ts",
    motif: "désormais",
    ancre: "qui lit déjà `opts.armurePortee`). Symétrique désormais : `ov?.armurePortee ?? cd?.armurePortee`.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/enemyProfile.ts",
    motif: "désormais",
    ancre: "désormais de sa RACE (canonique, partagée — cf. `raceById(baseSpeciesOf(species))`), surchargés",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/golden/ally-combat-vs-explore-parity.test.ts",
    motif: "désormais",
    ancre: "absente en combat, présente en explo. `rendersFromOwnInventory` route désormais sur l'origine.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/parts/bodies/extremites.ts",
    motif: "désormais",
    ancre: "tete/torse/jambes. Une tenue/armure PEUT désormais piloter ces zones (parts/*/types.ts). La botte",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/parts/equipment.ts",
    motif: "désormais",
    ancre: "armure de statblock non-portée ne produit désormais AUCUN item (`synthArmour`, #774) : plus",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/parts/injuries.test.ts",
    motif: "désormais",
    ancre: "// Prothèse PORTÉE par `trappingId` STABLE (≠ libellé) — c'est ce que `worn()` matche désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/parts/tenues/tenues.test.ts",
    motif: "désormais",
    ancre: "// un id de CLASSE (defs supprimés) retombe désormais sur Nu, jamais sur une tenue générique",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/parts/traitVisuals.test.ts",
    motif: "désormais",
    ancre: "un Nain (barbe en layer positif) garde ses cornes de trait — désormais MULTI-VUES (3 calques)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/quadruped/deco-stock.fixture.ts",
    motif: "désormais",
    ancre: "désormais `encolure#profile`, elle ne réclame plus les vues de bout (solde du stock des morts,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/quadruped/harnais/quad-harnais.test.ts",
    motif: "désormais",
    ancre: "(recollage byte-identique), désormais rejouable pour tout set futur. Contrôle NÉGATIF sur la",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/quadruped/heads/defs/boeuf.ts",
    motif: "désormais",
    ancre: "désormais en FRAGMENTS nommés, et le plan relatif de chacun est son RANG dans la chaîne",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/quadruped/heads/defs/boeuf.ts",
    motif: "désormais",
    ancre: "désormais de la robe, voilée d'ombre — une forme qui se devine DERRIÈRE, jamais un trou noir.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/rig/quadruped/quad-vues-ratchet.test.ts",
    motif: "désormais",
    ancre: "si l'os porte désormais un art dans cette vue (solde réel) ; supprimer la clé `deco` pour",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/MondeDeCampagne.tsx",
    motif: "désormais",
    ancre: "recevaient ; la masse est désormais CUITE en bloc (`bakeWorldGeometry` prend la scène entière),",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/MoveOverlays.test.tsx",
    motif: "désormais",
    ancre: "// `order`/`turn`/`movementUsed` : le badge dit désormais ce que le geste fait du Mouvement du Tour",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/escalade-et-chute-par-l-arete.test.tsx",
    motif: "désormais",
    ancre: "même, le geste appelé est le même, et la GÉOMÉTRIE est désormais celle du lift MÉTRIQUE — mesurée",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/escalade-et-chute-par-l-arete.test.tsx",
    motif: "désormais",
    ancre: "que la projection unique corrige : ils suivent désormais le sol qu'on voit.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/marques-parite.test.tsx",
    motif: "désormais",
    ancre: "CHEMIN qui est désormais celui du jeu.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/modele-forme.test.ts",
    motif: "désormais",
    ancre: "a désormais un producteur ailleurs : le DESSOUS d'un décor volumique, qui porte son propre dehors.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/pick-parity.test.tsx",
    motif: "désormais",
    ancre: "manque : elle rapporte désormais les DEUX, et par la MÊME fonction que le hook.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/pov-brume.test.tsx",
    motif: "désormais",
    ancre: "prennent désormais le MÊME scalaire que les lampes (`ambianceLum`) — c'est le CÂBLAGE de bout en",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/projection.ts",
    motif: "désormais",
    ancre: "`Dims.yawDeg` → `tileCenter`, qui partage désormais SA rotation et SA cadence).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/redessin-pilote.test.tsx",
    motif: "désormais",
    ancre: "désormais quelque chose de peint là où il n'y avait rien.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/stage-tons-lumiere.test.tsx",
    motif: "désormais",
    ancre: "// ÉCART ASSUMÉ (le seul) : la lampe naît désormais ORANGE et VACILLANTE au lieu de blanche et fixe.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/stage/weather-boucle.test.tsx",
    motif: "désormais",
    ancre: "que l'averse TIENT tant qu'elle tombe (#1378) — c'est par là que la boucle de chute passe désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/gameIso/token-chrome-alveoles.test.ts",
    motif: "désormais",
    ancre: "du joueur. Les places sont désormais RÉSERVÉES (même compte que le rack du portrait) et fixes.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/i18n/messages/fr.ts",
    motif: "désormais",
    ancre: "(Les Résistances Empoisonné/Sonné sont désormais data-driven — leur journal vient des ops",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/i18n/messages/fr.ts",
    motif: "désormais",
    ancre: "arrivé le premier sous `rv.loc*` ; le moteur en porte désormais les HUIT, la navigation",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/i18n/messages/fr.ts",
    motif: "désormais",
    ancre: "— sans accent), le CÔTÉ de dérive et les Compétences lancées (Voile/Ramer/Résistance, désormais lues",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/i18n/messages/fr.ts",
    motif: "désormais",
    ancre: "`craft.*`, LDB 60 l.7/11/42). La fonction rend désormais un id STABLE ; ces clés en sont l'affichage.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/name-field-guard.test.ts",
    motif: "désormais",
    ancre: "`GallerySpecimen` que l'ancienne version à pile ratait) est désormais couvert.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/raw-ref-integrity.test.ts",
    motif: "désormais",
    ancre: "« Degré de plus » dans tout le LDB) — l'appui RAW était fabriqué, la garde le refuse désormais à",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/prop-footprint-occupancy.test.ts",
    motif: "désormais",
    ancre: "déclarée dans `props.json` couvre désormais TOUTES ses cases dans TOUTE scène livrée, y compris",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/test-scenarios/15-commerce-fluvial.test.ts",
    motif: "désormais",
    ancre: "// Les jets du JOUR fluvial (et l'exposition) sont désormais une cascade influençable : la drainer.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/test-scenarios/42-belier-porte.ts",
    motif: "désormais",
    ancre: "de MÊLÉE servie se mesure depuis l'EMPREINTE DE LA COQUE (#210, `meleeWarMachineHullOf`), désormais 2×2",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/test-scenarios/duel-naval.test.ts",
    motif: "désormais",
    ancre: "Corruption d'un héros À BORD : #421, les pré-tirés suivent désormais les règles de création, ces",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/test-scenarios/opera.test.ts",
    motif: "désormais",
    ancre: "La salle est désormais COMPILÉE depuis un `MapSpec` par `buildScene` (headless-editor) : la grille",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/test-scenarios/piege-caveau.test.ts",
    motif: "désormais",
    ancre: "« Le Caveau piégé » est du CONTENU pur (données éditeur), désormais produit par `buildScene(MapSpec)`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/scenes/test-scenarios/voyage.test.ts",
    motif: "désormais",
    ancre: "/** Les 5 sous-scènes sont désormais produites par `buildScene(MapSpec)` (WorldMap/extraScenes restent sur",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/aa-critical-wiring.test.ts",
    motif: "désormais",
    ancre: "// #153 — `applyCriticalToTarget` passe désormais `now: get().gameTime` à `applyOps` : sans ce fil, un",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/aa-critical-wiring.test.ts",
    motif: "désormais",
    ancre: "// #153 — `applyCriticalToTarget` passe désormais `location: loc` à `applyOps` : l'op `disarm` (« Vous",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/advancement.test.ts",
    motif: "désormais",
    ancre: "// `option.label` est désormais une clé de câblage OPAQUE (refKey) ; `display` porte le texte.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/authorPerils.ts",
    motif: "désormais",
    ancre: "l'environnement ne voyait jamais. Chaque péril est désormais UNE étape (`worldStep`, évaluation",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/broken-recovery.test.ts",
    motif: "désormais",
    ancre: "Récupération du Brisé (LDB 16 l.54-58) — désormais 100 % DATA-DRIVEN (etats.json `brise.effects`,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/buy-spell.test.ts",
    motif: "désormais",
    ancre: "désormais les règles de création, leur quota de sorts mineurs varie avec leur seed) : BFM 2,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cascade-consequence-guard.test.ts",
    motif: "désormais",
    ancre: "PÉRIMÈTRE INVERSÉ #410 (2026-07-13) : la garde balaie désormais TOUT `src/state` + `src/engine`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cascade-step-stake-guard.test.ts",
    motif: "désormais",
    ancre: "pour router des étapes DÉJÀ mintées), et la surface se dérive désormais des PORTEURS des étapes",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cascade.ts",
    motif: "désormais",
    ancre: "(`openSequence`) : les deux sont désormais fermés par le type.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cascade.ts",
    motif: "désormais",
    ancre: "désormais sa propre copie. La garder ici la ferait rejouer au rechargement d'une sauvegarde.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cascade.ts",
    motif: "désormais",
    ancre: "restante à préserver). Ne ressuscite JAMAIS le slot actif (propriété d'un AUTRE contexte désormais,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cast-intent-ownership.test.ts",
    motif: "désormais",
    ancre: "possession). Une surface nulle ou partielle est donc désormais un ÉCHEC, pas un état de fait.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/cast-resilience-prejet.test.ts",
    motif: "désormais",
    ancre: "résout désormais contre la cible que le jet naturel aurait employée (`castTestTarget`).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combat-event-bus-orphans.test.ts",
    motif: "désormais",
    ancre: "#316 — les triggers ORPHELINS (jamais émis) sont désormais CÂBLÉS au bus (`emitCombatEvent`) à leur",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combat-event-bus-orphans.test.ts",
    motif: "désormais",
    ancre: "`applyOpposedCritical` émet désormais `onCrit` via le bus → les Atouts d'arme « sur Critique » (Taillade",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combat-hardcode-guard.test.ts",
    motif: "désormais",
    ancre: "désormais COMPTÉ. Stock révélé (aucun de ces sites n'était du hardcode NOUVEAU, seulement",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combat-optional-rules.test.ts",
    motif: "désormais",
    ancre: "Mutualisée via `enemyAutoDeviate`, elle respecte désormais la règle (bug rule-gate corrigé). Armure",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combat/roundHooks.ts",
    motif: "désormais",
    ancre: "autorise désormais les effets `on:'self'` sur une cible hors-combat, on filtre donc ici).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combatGate.ts",
    motif: "désormais",
    ancre: "// `aiDriven` vit désormais avec les primitives d'« qui pilote quoi » (`netOwnership`, dont dépend",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combatGeometry.ts",
    motif: "désormais",
    ancre: "inférieure dont la case est désormais SOUS son empreinte (LDB 85 l.373-374 : un plus grand « se",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/combatants.ts",
    motif: "désormais",
    ancre: "borne d'emplacement de héros la cite désormais, jamais un chiffre.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/corruption-lot-e.test.ts",
    motif: "désormais",
    ancre: "/** Franchit le seuil : le Test de Résistance est désormais une MODALE (kind 'seuil') —",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/crit-test-porte.test.ts",
    motif: "désormais",
    ancre: "Il naît désormais comme une ÉTAPE, et c'est le socle (`resolveFlowTest`) qui décide de sa surface.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/crit-test-porte.test.ts",
    motif: "désormais",
    ancre: "ignorait les États du jeteur — donc sans Chance, sans Pacte, sans Résilience. Ils naissent désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/curation-lot8.test.ts",
    motif: "désormais",
    ancre: "`spellSupport` reçoit désormais `spell` directement (SpellData — données JSON).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/curation-lot8.test.ts",
    motif: "désormais",
    ancre: "// Lumière émet désormais une VRAIE lumière (op `light` → brouillard de guerre) : volet mécanique +",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/devtools.ts",
    motif: "désormais",
    ancre: "'combat' — #345, la victoire est désormais différée tant qu'UNE cascade est ouverte). Recette : on",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/flow.ts",
    motif: "désormais",
    ancre: "FlowTest/TriggeredEffect), l'évaluation des Conditions et tous les helpers PURS vivent désormais en",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/flowVerbs.ts",
    motif: "désormais",
    ancre: "de Résistance. Les DEUX flux qui l'exposent ont désormais leur route par PORTEUR — `opposition`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/flowtest-derived-stake.test.ts",
    motif: "désormais",
    ancre: "désormais l'enjeu au TYPE) → `resolveStake` (la porte unique de la surface).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/footprint.test.ts",
    motif: "désormais",
    ancre: "leur case du seul fait que leur corps a désormais une empreinte. Liste NOMINATIVE : un",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/footprint.ts",
    motif: "désormais",
    ancre: "désormais dérivées.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/heal.test.ts",
    motif: "désormais",
    ancre: "// plafond relevé : un soin de Blessures ultérieur peut désormais atteindre le max complet",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/i18n-narration-guard.test.ts",
    motif: "désormais",
    ancre: "d'un fichier non listé. Le scan balaie désormais TOUT `src/engine` + `src/state` (walk récursif) ;",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/i18n-narration-guard.test.ts",
    motif: "désormais",
    ancre: "103 tenus (V8c₃, rattrapé par le juge). Désormais, un chiffre faux rougit. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/i18n-narration-guard.test.ts",
    motif: "désormais",
    ancre: "littéral-là n'est PAS une ligne de journal ; il est désormais compté ICI, à sa place.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/in-battle-find-guard.test.ts",
    motif: "désormais",
    ancre: "PÉRIMÈTRE ÉTENDU #410 (2026-07-13) : le scan couvre désormais `src/state` + `src/ui` + `src/gameIso`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/interlude-activities.test.ts",
    motif: "désormais",
    ancre: "`blocked` au catalogue, la porte `interludeActivity`/`openCatalogActivity` refuse désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/lineOfSight.ts",
    motif: "désormais",
    ancre: "// #805 : les cases de zone portent désormais l'étage (`z` du souffleur/centre) — la fumée d'un étage",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/magic-composant.test.ts",
    motif: "désormais",
    ancre: "// #152 : la rencontre `enc-mutants` spawne le Mutant du bestiaire, désormais flagué",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/man-emplacement.test.ts",
    motif: "désormais",
    ancre: "hero sert désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/maneuver-effects.test.ts",
    motif: "désormais",
    ancre: "Hurlement fantomatique porte désormais un nœud Flow `test` (Lot 4a) enfoui dans son Flow",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/multitile-target.test.ts",
    motif: "désormais",
    ancre: "la case du bord OPPOSÉ est désormais RECONNUE adjacente (le cœur du correctif)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/netOwnership.test.ts",
    motif: "désormais",
    ancre: "// La défense est désormais une étape `jet:'defense'` de la cascade `combat` (pendingDefense = porteur de",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/out-of-combat-upkeep.test.ts",
    motif: "désormais",
    ancre: "// requis par le Test de Résistance d'Empoisonné, désormais résolu INLINE hors combat (RAW l.66-72)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/pendings.ts",
    motif: "désormais",
    ancre: "pour enchaîner sur la pause de début de Round (la Peur est désormais marquée testée ce Round). */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/player-text-ratchet.test.ts",
    motif: "désormais",
    ancre: "- la météo de Scène (`Scene['weather']`) : son libellé FR vit désormais SUR LE NŒUD",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/port-sell-cargo.test.ts",
    motif: "désormais",
    ancre: "Marchandage est désormais une CASCADE (`openRoll` par étape, enchaînée via `chainStep`,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/preferences-migration.test.ts",
    motif: "désormais",
    ancre: "// désormais persisté du bon côté",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/preview-attack.test.ts",
    motif: "désormais",
    ancre: "difficile (−30) ». Les deux lisent désormais la même liste (`defenseTargetMods`) et la même",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/projet-migration-10-vers-11.test.ts",
    motif: "désormais",
    ancre: "désormais en clé inconnue) mais une ACTION AUTHORÉE de l'enveloppe `usable` — et cette enveloppe,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/projet-migration-5-vers-6.test.ts",
    motif: "désormais",
    ancre: "et un statbloc EMBARQUÉ s'annonce désormais (`type: 'statblock'`, EXIGÉ par `customStatblockSchema`).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/projet-migration-9-vers-10.test.ts",
    motif: "désormais",
    ancre: "QUESTION : l'utilisabilité d'une entité se DÉRIVE désormais de ce qu'elle offre (`estUtilisable`,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/resistance-menace.test.ts",
    motif: "désormais",
    ancre: "la spec du talent sont désormais des ids stables (Phase 3) : exposition à la Corruption ('corruption'),",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/rest-lodging-price-source.test.ts",
    motif: "désormais",
    ancre: "`src/state/merchants/service-trappings.test.ts`). Convergence #343 : `restCost` RÉSOUT désormais ces",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/restFlow.ts",
    motif: "désormais",
    ancre: "// 2ᵉ Test du dessoûlage (l.485), désormais influençable : le DR fixe la durée de la gueule de bois.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/reveal-routing.test.ts",
    motif: "désormais",
    ancre: "// Dégâts d'Hémorragique désormais data-driven (effects onRoundEnd → wounds) : le journal porte la",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/reveal.test.ts",
    motif: "désormais",
    ancre: "type le refuse désormais (`CascadeTableDone`) ; ce couple test + directive en est la mesure.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/roll-action-label-guard.test.ts",
    motif: "désormais",
    ancre: "donc TOUJOURS LÀ, et le scan le suit désormais jusqu'à sa clé. */",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/rollSeam.test.ts",
    motif: "désormais",
    ancre: "// `cascadeAppliers['progression']` est désormais le VRAI applier de mer (#275 Décision 4 cran 2, `seaVoyageFlow.ts`)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/rollflow-outcome-invariant.test.ts",
    motif: "désormais",
    ancre: "désormais sa fenêtre du succès de la LIGNE (`row.d.success`) : si une modale y pose une issue",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/roomPortals.test.ts",
    motif: "désormais",
    ancre: "#1416 LOT 1 — l'accessibilité des sorties se lit désormais sur un ÉTIQUETAGE de composantes",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/saves-flow.test.ts",
    motif: "désormais",
    ancre: "héros. Il portait la DONNÉE `Amputation` (`{difficulty, sequels, loss…}`) ; il porte désormais le",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/saves-flow.test.ts",
    motif: "désormais",
    ancre: "// La porte qui monte désormais ces lignes est celle de tout le monde : les appliers de nuit",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/saves-flow.test.ts",
    motif: "désormais",
    ancre: "// La fenêtre de suspension (Racine de terre, fenêtre de Détermination) nomme désormais sa source par",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/saves-flow.test.ts",
    motif: "désormais",
    ancre: "vivent désormais en op PASSIVE sur l'`ActiveEffect` du sort (`passive`), matérialisés en pions",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/sea-finition.test.ts",
    motif: "désormais",
    ancre: "désormais UNE cascade `purpose:'travelDay'` (#275 Ronde 2 cran 3) : chaque étape est soit MONO",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/sea-finition.test.ts",
    motif: "désormais",
    ancre: "// Seam de jet (#273 Étape 2) : Cartographie est désormais une étape de CASCADE influençable —",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/seaVoyageFlow.ts",
    motif: "désormais",
    ancre: "Lot 1) est désormais écrit par `commitStep` depuis les `consequences` retournées (`freeCons`), pas",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/self-maneuver-transform.test.ts",
    motif: "désormais",
    ancre: "désormais seul le retour est proposé",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/sequence-contrat-socle.test.ts",
    motif: "désormais",
    ancre: "// Ce que fait `startCombat` du point de vue de la garde : le slot appartient désormais à un AUTRE",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/sequence-parite-catalogue.test.ts",
    motif: "désormais",
    ancre: "accent) — elle vient désormais de la donnée (`riverForceLabel`), qui dit « Modéré ».",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/ship-crew-hit-porte.test.ts",
    motif: "désormais",
    ancre: "`applyCrewHit`, avec le RNG du combat, marin par marin. Il naît désormais comme UNE BANDE — une",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/ship-maneuver.test.ts",
    motif: "désormais",
    ancre: "(openCrewTestPending ET shipManeuverParams, consommé par deriveManeuverFromCrew) — site canonique désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/shipManeuver.ts",
    motif: "désormais",
    ancre: "de rôle à 110 forçait un DR 11 et rend désormais DR 9 (cible 99). Alignement VOULU : les deux",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/skillIdMigration.ts",
    motif: "désormais",
    ancre: "Compétences d'un Combattant portent désormais l'`id` STABLE nu, comme toute référence de la",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/sleep-wake.test.ts",
    motif: "désormais",
    ancre: "`narrative` « arbitrage MJ », désormais MÉCANISÉ (le MJ, c'est le moteur). Une cible qui dort EST Inconsciente,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/stepBrand.ts",
    motif: "désormais",
    ancre: "la refuse désormais à la DÉCLARATION. Il ne mord PAS sur une signature qui EMPLOIE la marque",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/targeting.test.ts",
    motif: "désormais",
    ancre: "le survol dit ce que le CLIC fera, or le clic dépend désormais de la case Charge.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/targetingModes.ts",
    motif: "désormais",
    ancre: "offensif non-Projectile (Choc, Sommeil…) se cible désormais sur l'ennemi, comme le tir.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/trample.test.ts",
    motif: "désormais",
    ancre: "// La Marche consommée par l'approche est désormais TRACÉE — la gate de Se cabrer (l.205 ci-dessus,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/travel-carto.test.ts",
    motif: "désormais",
    ancre: "Voyage — poste « Établir des cartes » (EDOC 8 l.161) : Test ÉTENDU inter-Étapes, désormais UNE RANGÉE",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/triggered-effects.test.ts",
    motif: "désormais",
    ancre: "// NB : Affamé porte désormais un nœud Flow `test` (Lot 4a) → routé cadence-aware, plus un jet inline",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/triggered-effects.test.ts",
    motif: "désormais",
    ancre: "Affamé (LDB 85) porte désormais un nœud Flow `test` (Lot 4a) : `onKill` → Test de FM Accessible →",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/vessel-morale.test.ts",
    motif: "désormais",
    ancre: "inchangé ; en cadence manuelle un équipage salarié convoque désormais le Conseil de bord (#229, ci-dessous).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/worldMap.ts",
    motif: "désormais",
    ancre: "la donnée, et le schéma l'EXIGE désormais (`defs-scenes/communs.ts`) — sans ce passage, tout",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/worldMap.ts",
    motif: "désormais",
    ancre: "même raison : un document embarqué s'annonce dans la donnée, et le schéma l'EXIGE désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/state/worldMap.ts",
    motif: "désormais",
    ancre: "seule PRÉSENCE — dit désormais `assise: true`. Sans ce passage, un projet de bibliothèque",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/CrewTestModal.test.tsx",
    motif: "désormais",
    ancre: "VOYAGE sont désormais des étapes de la cascade du jour (#275 Ronde 2 cran 3, `CascadeModal`) — cette",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/CrewTestModal.tsx",
    motif: "désormais",
    ancre: "(hors combat) sont désormais des étapes de la cascade du jour (#275 Ronde 2 cran 3, `CascadeModal`) —",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/EtatPanel.test.tsx",
    motif: "désormais",
    ancre: "psychologie/surcharge). Les États actifs sont désormais des CHIPS compactes (0 PlaqueRow), et la",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/InterludeScreen.test.tsx",
    motif: "désormais",
    ancre: "composent désormais les mêmes sources : `activityTestMod` → `activityModLines`.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/RollShell.test.tsx",
    motif: "désormais",
    ancre: "(Le préfixe 🎲 est désormais l'icône <Icon id=\"nav/dice\"> — on vérifie le libellé texte.)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/RollShell.test.tsx",
    motif: "désormais",
    ancre: "l'accole désormais elle-même, dérivé de la MÊME entrée d'enjeu que la phrase.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ShipStationsPanel.tsx",
    motif: "désormais",
    ancre: "suit désormais cette règle (arbitrage user 2026-09-04) : les stations n'y sont plus l'exception.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/StateChips.test.tsx",
    motif: "désormais",
    ancre: "désormais (`chipNom`, source unique), et la MÊME forme sert la fiche (« Effets actifs ») : une",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/TravelRecapModal.test.tsx",
    motif: "désormais",
    ancre: "depuis le cas arrivée, désormais amincie).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/active-modal.test.ts",
    motif: "désormais",
    ancre: "Arbitre de modales (R2, désormais REGISTRE state/modalArbiter) : une seule modale de combat à",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/active-modal.test.ts",
    motif: "désormais",
    ancre: "La SITUATION est désormais portée par la cascade-hôte ouverte à l'incantation (CascadeModal → CastModal).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/codex-edit-charge-discriminee.test.tsx",
    motif: "désormais",
    ancre: "// #1686 tenait à `materials` : le stock NOMME désormais ses clés, si bien qu'une reprise de champs",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/codex-edit-save-transaction.test.tsx",
    motif: "désormais",
    ancre: "silence. La pose est désormais TRANSACTIONNELLE — le refus REPREND l'état d'avant.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/registry-enveloppe.test.ts",
    motif: "désormais",
    ancre: "#1690 (correctifs du lot 3) : `depuisEnveloppe` projette désormais `maison` — l'arbitrage d'une",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/registry-enveloppe.test.ts",
    motif: "désormais",
    ancre: "désormais les ops de chaque bande (primitive `opRows` — chips codex-liées + `rollTable` expansé)",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/registry-enveloppe.test.ts",
    motif: "désormais",
    ancre: "`taille` 0 → 24). La clé projetée qui bouge est `maison`, désormais portée par TOUS les items —",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/registry.ts",
    motif: "désormais",
    ancre: "// PA / arme naturelle / traits conférés sont désormais des GameOps du `passive` (ap /",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/relations.test.ts",
    motif: "désormais",
    ancre: "est désormais une clé mono-catégorie → la JAUGE.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/compendium/relations.ts",
    motif: "désormais",
    ancre: "// 15) Lieu ← sous-lieux (inversion de location.parent, désormais un id de parent).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/coop-surfaces-combat.test.tsx",
    motif: "désormais",
    ancre: "// La modale s'ouvre ENSUITE (jet du héros distant) : c'est elle qui parle désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/echap-intention-consomme.test.tsx",
    motif: "désormais",
    ancre: "désarme, et les suivants — l'intention désormais nulle — retombent sur `toggle-menu`.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/editor/no-datalist.test.ts",
    motif: "désormais",
    ancre: "PÉRIMÈTRE ÉTENDU #410 (2026-07-13) : la garde balaie désormais TOUT `src/ui` (walk récursif) au",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/forcedDieRow.pre-roll.test.tsx",
    motif: "désormais",
    ancre: "porte désormais SA ligne ; le libellé VISIBLE reste l'état du champ (offre / marque).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/forcedDieRow.pre-roll.test.tsx",
    motif: "désormais",
    ancre: "rangée détient sa poignée LOCALE. La coquille tient désormais un REGISTRE de poignées et applique",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/forcedDieRow.ts",
    motif: "désormais",
    ancre: "le dos/piétinement — ne le font plus), et une modale qui n'en avait jamais l'offre désormais.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/registry-id-branch-guard.test.ts",
    motif: "désormais",
    ancre: "sortent de la liste, `combatFlow.ts` passe de 2 à 1. Ce que l'entrée DÉCLARE désormais : la séquelle",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/registry-id-branch-guard.test.ts",
    motif: "désormais",
    ancre: "mesure brute résout désormais les CONSTANTES DE MODULE (`const X = 'lit'` → `=== X`). Quatre sites",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/registry-id-branch-guard.test.ts",
    motif: "désormais",
    ancre: "sites qui la testent) : la comparaison reste la MÊME et reste COMPTÉE — le scanner brut résout désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/sheetAlarms.test.ts",
    motif: "désormais",
    ancre: "(désormais `EffectChips`). Contrat : détecter les afflictions par `key` d'identité + `label`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ui-ratchets.test.ts",
    motif: "désormais",
    ancre: "pour que plus aucun panneau ne recode la rangée : 13 sites de l'éditeur la composent désormais,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ui-ratchets.test.ts",
    motif: "désormais",
    ancre: "// #839 : -1 (1 → 0, entrée retirée) — la remise au défaut d'une règle (`↺`) compose désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ui-ratchets.test.ts",
    motif: "désormais",
    ancre: "exemption des primitives — tout `<button className={fn(...)}>` NOUVEAU doit désormais soit exposer un",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ui-ratchets.test.ts",
    motif: "désormais",
    ancre: "Une classe qui s'y planquerait sans être partagée ni cataloguée compte donc désormais comme fuite.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ui-ratchets.test.ts",
    motif: "désormais",
    ancre: "`.hero-present-chips` repassent mono-consommateur — le détail candidat compose désormais `SkillChip`/",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/ui-ratchets.test.ts",
    motif: "désormais",
    ancre: "rejoints au #1153 (sa rangée adverse existe désormais dès l'ouverture, masquée par le calendrier).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "src/ui/useRollFrisson.ts",
    motif: "désormais",
    ancre: "@param opts.frisson  Anime avant de résoudre (défaut : TRUE — #396, tout jet roule désormais ;",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/arene/zones1-7.mjs",
    motif: "désormais",
    ancre: "// empreinte 3×3 : (24,4) chevaucherait les « Chapeaux moirés » (26,4), désormais bloquants",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/docs/build-all.mjs",
    motif: "désormais",
    ancre: "périmé, et la gate `docs:empreinte` refusait 7 min plus tard (#1773) ; désormais son `--check` rouge",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/gates/ecrivainsAtteints.test.mjs",
    motif: "désormais",
    ancre: "désormais pour ne demander que sur un tag NEUF ; l'arbre versionné n'est jamais écrit.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/gates/ecrivainsAtteints.test.mjs",
    motif: "désormais",
    ancre: "// +1 le 2026-09-19 (#1825 lot B) : le détecteur des sauts de folio porte désormais UN",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/gen-sorts-doc.mts",
    motif: "désormais",
    ancre: "Migration #5 : les métadonnées de résolution (durée, ZdE, etc.) vivent désormais",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/git-hooks/pre-commit.mjs",
    motif: "désormais",
    ancre: "l'étape docs de `ops:publier` — qui juge désormais aussi les pieds des cibles `check: false`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/cssConservation.mjs",
    motif: "désormais",
    ancre: "plus, ou l'emporte désormais, sur une déclaration CONSERVÉE visant une classe",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/empreinteStage.mjs",
    motif: "désormais",
    ancre: "juge désormais aussi les pieds des cibles `check: false` (`piedsDesNonVerifiables`, #1773) ; la",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/groundingCorpus.mjs",
    motif: "désormais",
    ancre: "prose qui parle d'elle-même. Fix : `resolves` scope désormais STRICTEMENT à la section structurelle",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/labelLogic.mjs",
    motif: "désormais",
    ancre: "`conditionIds`/`conditionIdInText` portent désormais la couture dans `src/data/index.ts`. Cliquet",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/progressionSchemas.mjs",
    motif: "désormais",
    ancre: "rapprochement par folio aurait apparié des Carrières entre elles. Ces écarts sont désormais NULS et",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/rollSeamWhitelist.mjs",
    motif: "désormais",
    ancre: "`WORLD_DIE_SUBTRACTED_STOCK` (plus bas) PUBLIE désormais ce qu'elle soustrait, fichier par fichier ;",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/rollSeamWhitelist.mjs",
    motif: "désormais",
    ancre: "avec le chemin eager de l'entretien : `runDailyUpkeep` EXIGE désormais sa porte (`onDeferTest`",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/rollSeamWhitelist.mjs",
    motif: "désormais",
    ancre: "il est désormais une garde ANTI-RÉCIDIVE, et c'est le test qui le rend mordant (tout fichier",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/slotsStock.mjs",
    motif: "désormais",
    ancre: "// 76→72 (#1687 lot 3-I) : cette ligne dérive de `scan.formes` (`champsSansSlot`), et 4 objets `effect` d'`arene-projet.json` en sortent — n",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/slotsStock.mjs",
    motif: "désormais",
    ancre: "25 → 26 (#1599) : l'État *Exténué* du Malaise (LDB 20 l.188) s'écrit désormais en op `condition` du canal passif",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/guards/lib/stocksNominatifs.mjs",
    motif: "désormais",
    ancre: "(#1711 T2-T4, puis les ancres sans contenu #1727 T2 : leurs entrées nomment désormais le chapitre",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/hooks/exception-add-guard.test.mjs",
    motif: "désormais",
    ancre: "adversarial (2026-07-13) échouent désormais, et les cas légitimes restent silencieux.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/hooks/git-destructive-guard.mjs",
    motif: "désormais",
    ancre: "l'autre : un `Set-Location <worktree lié>; git reset --hard` passe désormais en silence comme son",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/hooks/memoire-tombale-guard.mjs",
    motif: "désormais",
    ancre: "daté légitime (49 lignes pour le premier mot, 28 pour « désormais », 43 pour le troisième) : les",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/hooks/stocks-nominatifs.test.mjs",
    motif: "désormais",
    ancre: "qui ment pour tout appelant hors CI (diagnostic, sonde, revue). Un tel appel est désormais un",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/loup-et-saumure/generate.mjs",
    motif: "désormais",
    ancre: "accepte désormais créature ∪ véhicule (#218) — un `ref` de NAVIRE (`vehicles.json` : `cogue`/`langskip`/",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-27-l1b-2e-donnees-rubriques-id.mjs",
    motif: "désormais",
    ancre: "d'un cran plus stable seulement. Toute rubrique peut désormais porter sa note.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-27-l1b-3c-stars-ops.mjs",
    motif: "désormais",
    ancre: "PROSE par le détecteur de structures (rôle `prose`, cible `desc`) ; il porte désormais le nom du",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-27-l1b-3e-tavern-poteffectid.mjs",
    motif: "désormais",
    ancre: "`resolveSequencePotTurn`. La clé porte désormais ce qu'elle contient — suffixe `Id` du dépôt pour",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-27-l1b-4b-actions-maison-raison.mjs",
    motif: "désormais",
    ancre: "le contrat que le refine gardait est désormais porté par le TYPE seul (`z.string().min(1)`).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-28-l1b-7c-progression-schemas-livres.mjs",
    motif: "désormais",
    ancre: "elles décrivent le def, pas le document — elles vivent désormais au JSDoc de",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-29-l1b-15b-projet-forme-6.mjs",
    motif: "désormais",
    ancre: "1ʳᵉ clé. Le schéma l'EXIGE désormais (`defs-scenes/communs.ts`, `z.literal('statblock')`), donc",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-30-progression-key-vers-characteristic.mjs",
    motif: "désormais",
    ancre: "L'artefact étant GÉNÉRÉ, `scripts/data/gen-progression-schemas.py` écrit désormais cette forme —",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-08-31-1552-projet-sannonce.mjs",
    motif: "désormais",
    ancre: "- `type: 'projet'` à la racine (l'enveloppe de `document()` l'exige désormais,",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-01-1463-monnaie-brass.mjs",
    motif: "désormais",
    ancre: "portent désormais `brass`) — un montant oublié ailleurs dans ces 4 documents est une anomalie.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-02-1507-recettes-en-metres.mjs",
    motif: "désormais",
    ancre: "ÉCRIT DÉSORMAIS (`RAISONS`) — les deux migrations convergent, dans n'importe quel ordre de rejeu.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-02-1680-props-provenance.mjs",
    motif: "désormais",
    ancre: "`affinerEntree` (`src/data/schemas/defs/props.ts`) l'exige désormais à l'entrée.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-03-1509-foot-volumique-mort.mjs",
    motif: "désormais",
    ancre: "Le refine `affinerEntree` (`src/data/schemas/defs/props.ts`) refuse désormais la co-présence à",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-03-1509-murale-1x2.mjs",
    motif: "désormais",
    ancre: "désormais la sienne, l'abord redevient droit — (0,−1), depuis la salle, en face de son siège",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-05-1599-passifs-par-palier.mjs",
    motif: "désormais",
    ancre: "(Modéré), cette pénalité passe à -20. » Le palier S'AJOUTE désormais à `passive` au lieu de le",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-07-1691-relief-en-donnee.mjs",
    motif: "désormais",
    ancre: "désormais au lieu de choisir `pierre` en dur ; le schéma exige le champ ⟺ `solidHeightM`.",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-17-1695-etats-portes-pour-la-duree-du-sort.mjs",
    motif: "désormais",
    ancre: "Surincantation de Durée. Elle porte désormais `carried: true` (`src/engine/ops.ts`) : l'État est posé",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/migrations/2026-09-18-1797-minimum-de-1-round-dans-la-formule.mjs",
    motif: "désormais",
    ancre: "portait une clause qui appartient à DEUX entrées de table. La borne basse est désormais un terme de",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
  {
    fichier: "scripts/raw/check-renvois.mjs",
    motif: "désormais",
    ancre: "renvoi se résout désormais (la retirer).",
    lot: "L7 désormais",
    date: "2026-09-26",
  },
];
