// ⚠️ GÉNÉRÉ par scripts/gen-registry.mjs — NE PAS ÉDITER À LA MAIN.
// Ajouter une entrée = déposer un fichier dans defs/ puis `npm run gen`.
import type { AppearanceElement } from './types';
import { element as e0 } from './defs/articulation-supplementaire-aux-jambes';
import { element as e1 } from './defs/barbe-naine';
import { element as e2 } from './defs/beaute-surnaturelle';
import { element as e3 } from './defs/bouche-supplementaire';
import { element as e4 } from './defs/cornes-asymetriques';
import { element as e5 } from './defs/cornes-demon';
import { element as e6 } from './defs/cornes-taureau';
import { element as e7 } from './defs/corpulent';
import { element as e8 } from './defs/court-sur-pattes';
import { element as e9 } from './defs/crane-pointu';
import { element as e10 } from './defs/crocs';
import { element as e11 } from './defs/doigts-distendus';
import { element as e12 } from './defs/ecailles-epineuses';
import { element as e13 } from './defs/ecailles';
import { element as e14 } from './defs/emacie';
import { element as e15 } from './defs/griffes';
import { element as e16 } from './defs/groin-poilu';
import { element as e17 } from './defs/langue-pendante';
import { element as e18 } from './defs/muscles-torse';
import { element as e19 } from './defs/museau-chien';
import { element as e20 } from './defs/oreilles-pointues';
import { element as e21 } from './defs/panse';
import { element as e22 } from './defs/pattes-danimaux';
import { element as e23 } from './defs/peau-brillante';
import { element as e24 } from './defs/pelage-massif';
import { element as e25 } from './defs/pelage';
import { element as e26 } from './defs/plaie';
import { element as e27 } from './defs/plumage';
import { element as e28 } from './defs/plumes-eparses';
import { element as e29 } from './defs/queue-rat';
import { element as e30 } from './defs/queue';
import { element as e31 } from './defs/suintement-de-pus';
import { element as e32 } from './defs/tentacule-epais';
import { element as e33 } from './defs/verrues';
import { element as e34 } from './defs/visage-inverse';

export const ELEMENT_DEFS: AppearanceElement[] = [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34];
