// ⚠️ GÉNÉRÉ par scripts/gen-registry.mjs — NE PAS ÉDITER À LA MAIN.
// Ajouter une entrée = déposer un fichier dans defs/ puis `npm run gen`.
import type { QualityDef } from './types';
import { quality as e0 } from './defs/ArmeDEquipe';
import { quality as e1 } from './defs/Desequilibree';
import { quality as e2 } from './defs/Destabilisante';
import { quality as e3 } from './defs/Infecte';
import { quality as e4 } from './defs/Salve';
import { quality as e5 } from './defs/Taillade';
import { quality as e6 } from './defs/TirDeZone';
import { quality as e7 } from './defs/a-enroulement';
import { quality as e8 } from './defs/a-explosion';
import { quality as e9 } from './defs/a-poudre-noire';
import { quality as e10 } from './defs/a-repetition';
import { quality as e11 } from './defs/assommante';
import { quality as e12 } from './defs/bacle';
import { quality as e13 } from './defs/dangereuse';
import { quality as e14 } from './defs/de-plaies-atroces';
import { quality as e15 } from './defs/defensive';
import { quality as e16 } from './defs/devastatrice';
import { quality as e17 } from './defs/empaleuse';
import { quality as e18 } from './defs/epuisante';
import { quality as e19 } from './defs/flexible';
import { quality as e20 } from './defs/immobilisante';
import { quality as e21 } from './defs/impenetrable';
import { quality as e22 } from './defs/imprecise';
import { quality as e23 } from './defs/incassable';
import { quality as e24 } from './defs/inoffensive';
import { quality as e25 } from './defs/laid';
import { quality as e26 } from './defs/leger';
import { quality as e27 } from './defs/lente';
import { quality as e28 } from './defs/magique';
import { quality as e29 } from './defs/partielle';
import { quality as e30 } from './defs/percutante';
import { quality as e31 } from './defs/perforante';
import { quality as e32 } from './defs/perturbante';
import { quality as e33 } from './defs/peu-fiable';
import { quality as e34 } from './defs/piege-lame';
import { quality as e35 } from './defs/pistolet';
import { quality as e36 } from './defs/points-faibles';
import { quality as e37 } from './defs/pointue';
import { quality as e38 } from './defs/pratique';
import { quality as e39 } from './defs/precise';
import { quality as e40 } from './defs/protectrice';
import { quality as e41 } from './defs/raffine';
import { quality as e42 } from './defs/rapide';
import { quality as e43 } from './defs/recharge';
import { quality as e44 } from './defs/solide';
import { quality as e45 } from './defs/taille';
import { quality as e46 } from './defs/volumineux';

export const QUALITY_DEFS: QualityDef[] = [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35, e36, e37, e38, e39, e40, e41, e42, e43, e44, e45, e46];
