import { writeFileSync } from 'node:fs';
import { Resvg } from '@resvg/resvg-js';
import { DEFS } from '../src/gameIso/sprites';
import { bonesToSvg } from '../src/gameIso/rig/renderBones';
import { resolveWing, WINGED_SPECIES } from '../src/gameIso/rig/winged/composeWing';
import { QUAD_DEATH } from '../src/gameIso/rig/quadruped/quadPose';
const rows = [['Dragon','profile'],['Griffon','profile'],['Pégase','profile']] as const;
const CW=420, CH=380, FEET=300, cells:string[]=[];
rows.forEach(([n,v],i)=>{ const sl=WINGED_SPECIES[n].sl, SC=1.2*Math.min(sl,1.6);
  const inner=bonesToSvg(resolveWing(n,v as any,QUAD_DEATH));
  const ox=10+i*CW, cx=(CW-8)/2;
  cells.push(`<g transform="translate(${ox},10)"><rect width="${CW-8}" height="${CH-10}" fill="#2b3142"/><line x1="0" y1="${FEET}" x2="${CW-8}" y2="${FEET}" stroke="#e06a4a" stroke-width="0.5" opacity="0.4"/><g transform="translate(${cx-60*SC},${FEET-150*SC}) scale(${SC})">${inner}</g><text x="${cx}" y="${CH-16}" text-anchor="middle" font-size="13" fill="#cdd">${n} MORT</text></g>`);
});
const W=10+rows.length*CW,H=CH+20;
const full=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}"><defs>${DEFS}</defs><rect width="${W}" height="${H}" fill="#11141c"/>${cells.join('')}</svg>`;
writeFileSync('public/qc/_qc-wingdeath.png', new Resvg(full,{background:'#11141c',fitTo:{mode:'width',value:Math.min(1900,W)}}).render().asPng());
console.log('OK _qc-wingdeath.png');
