import type { WeaponDef } from '../types';

export const weapon: WeaponDef = {
  slug: "fleau_grain",
  label: "Fléau à grain",
  type: "melee",
  group: "Fléau",
  target: "fléau agricole : battant de bois relié au manche par une lanière",
  art: "<!-- FLEAU A GRAIN (agricole) : long manche droit + COURTE laniere de cuir souple en articulation + gros battant cylindrique de bois clair. repere os 'arme' : poignee (0,0), battant vers -y, pommeau vers +y --><!-- ===== MANCHE long, droit, en bois ===== --><g stroke=\"#2a1a0c\" stroke-width=\"0.5\" stroke-linejoin=\"round\"><rect x=\"-2.2\" y=\"-25\" width=\"4.4\" height=\"34\" rx=\"1.8\" fill=\"#7a5226\"/><rect x=\"-2.2\" y=\"-25\" width=\"1.5\" height=\"34\" rx=\"0.7\" fill=\"#9a6e38\" opacity=\"0.6\" stroke=\"none\"/><!-- bague de prise / pommeau cote main --><rect x=\"-3\" y=\"6\" width=\"6\" height=\"3\" rx=\"1\" fill=\"#4a2f17\"/><!-- collet bois en haut du manche, ou s'attache la laniere --><rect x=\"-2.8\" y=\"-26.5\" width=\"5.6\" height=\"3\" rx=\"1\" fill=\"#5a3a1c\"/></g><!-- ===== COURTE LANIERE de cuir souple : articulation lache (double brin qui pendouille en S, gap net entre manche et battant) ===== --><g fill=\"none\" stroke-linecap=\"round\"><path d=\"M-1.6 -27 Q-5 -29 -4 -33 Q-3 -36 -5.5 -38\" stroke=\"#2e1c0a\" stroke-width=\"3\"/><path d=\"M-1.6 -27 Q-5 -29 -4 -33 Q-3 -36 -5.5 -38\" stroke=\"#8a5a2c\" stroke-width=\"1.6\"/><path d=\"M1.6 -27 Q-1 -30 -0.5 -34 Q0 -37 -3 -39\" stroke=\"#2e1c0a\" stroke-width=\"3\"/><path d=\"M1.6 -27 Q-1 -30 -0.5 -34 Q0 -37 -3 -39\" stroke=\"#8a5a2c\" stroke-width=\"1.6\"/></g><!-- anneaux de cuir noues aux deux bouts de la laniere (lacage) --><circle cx=\"0\" cy=\"-26\" r=\"2\" fill=\"none\" stroke=\"#2e1c0a\" stroke-width=\"1.5\"/><circle cx=\"-4.4\" cy=\"-38\" r=\"2\" fill=\"none\" stroke=\"#2e1c0a\" stroke-width=\"1.5\"/><!-- ===== BATTANT (le frappeur) : gros cylindre de bois clair, arrondi, incline, lie a la laniere par son talon ===== --><g transform=\"rotate(34 -5 -42)\"><!-- corps cylindrique : capsule pleine, bois clair --><rect x=\"-9.5\" y=\"-54\" width=\"9\" height=\"24\" rx=\"4.5\" fill=\"#a9763c\" stroke=\"#3a2410\" stroke-width=\"0.6\"/><!-- volume : flanc clair (lumiere) + flanc sombre (ombre) pour lire le rond --><rect x=\"-9.2\" y=\"-53.4\" width=\"2.6\" height=\"22.8\" rx=\"1.3\" fill=\"#c79356\" opacity=\"0.75\" stroke=\"none\"/><rect x=\"-2.8\" y=\"-53.4\" width=\"2.2\" height=\"22.8\" rx=\"1.1\" fill=\"#7a5226\" opacity=\"0.55\" stroke=\"none\"/><!-- calotte haute (bout arrondi du log) --><ellipse cx=\"-5\" cy=\"-53.5\" rx=\"4.4\" ry=\"1.8\" fill=\"#c79356\" stroke=\"#3a2410\" stroke-width=\"0.5\"/><!-- deux frettes de fer (anneaux de renfort du battant) --><rect x=\"-9.7\" y=\"-49\" width=\"9.4\" height=\"1.8\" rx=\"0.8\" fill=\"#3a3038\" stroke=\"none\"/><rect x=\"-9.7\" y=\"-38\" width=\"9.4\" height=\"1.8\" rx=\"0.8\" fill=\"#3a3038\" stroke=\"none\"/></g>",
};
