import type { WeaponDef } from '../types';

export const weapon: WeaponDef = {
  slug: "fleau_grain",
  label: "Fléau à grain",
  type: "melee",
  group: "Fléau",
  target: "fléau agricole : battant de bois relié au manche par une lanière",
  art: "<!-- FLEAU A GRAIN (agricole) : deux batons de bois (manche long + battant plus court) relies par une COURTE laniere de cuir, gap net entre les deux. repere os 'arme' : poignee (0,0), battant vers -y, pommeau vers +y --><!-- ===== MANCHE : long baton droit de bois, mince ===== --><g stroke=\"#2a1a0c\" stroke-width=\"0.5\" stroke-linejoin=\"round\"><rect x=\"-2\" y=\"-26\" width=\"4\" height=\"35\" rx=\"1.6\" fill=\"@cuirO\"/><rect x=\"-2\" y=\"-26\" width=\"1.4\" height=\"35\" rx=\"0.7\" fill=\"@cuir\" opacity=\"0.55\" stroke=\"none\"/><!-- pommeau cote main (renflement de prise) --><rect x=\"-2.9\" y=\"6\" width=\"5.8\" height=\"3.4\" rx=\"1.2\" fill=\"@cuirO\"/><!-- collet de fer en haut du manche, ou s'attache la laniere --><rect x=\"-2.7\" y=\"-27.5\" width=\"5.4\" height=\"2.6\" rx=\"0.9\" fill=\"@metal\" stroke=\"none\"/></g><!-- ===== COURTE LANIERE de cuir : double brin lache qui pendouille, GAP net entre manche et battant ===== --><g fill=\"none\" stroke-linecap=\"round\"><path d=\"M-1.4 -28 Q-4.5 -31 -3 -35\" stroke=\"#2e1c0a\" stroke-width=\"3.2\"/><path d=\"M-1.4 -28 Q-4.5 -31 -3 -35\" stroke=\"@cuirO\" stroke-width=\"1.7\"/><path d=\"M1.4 -28 Q-1 -32 -1 -36\" stroke=\"#2e1c0a\" stroke-width=\"3.2\"/><path d=\"M1.4 -28 Q-1 -32 -1 -36\" stroke=\"@cuirO\" stroke-width=\"1.7\"/></g><!-- anneaux de cuir noues aux deux bouts (lacage manche / lacage battant) --><circle cx=\"0\" cy=\"-27\" r=\"1.9\" fill=\"none\" stroke=\"#2e1c0a\" stroke-width=\"1.4\"/><circle cx=\"-2\" cy=\"-36.5\" r=\"1.9\" fill=\"none\" stroke=\"#2e1c0a\" stroke-width=\"1.4\"/><!-- ===== BATTANT : deuxieme BATON de bois (plus court, un peu plus gros que le manche mais clairement un baton, pas un tonneau), incline, lie a la laniere par son talon ===== --><g transform=\"rotate(30 -2 -38)\"><!-- corps : baton allonge, bois clair, coins arrondis doux --><rect x=\"-5.6\" y=\"-54\" width=\"6\" height=\"20\" rx=\"2.4\" fill=\"@cuir\" stroke=\"#3a2410\" stroke-width=\"0.6\"/><!-- veine de lumiere (flanc clair) + flanc d'ombre pour donner le rond du baton --><rect x=\"-5.3\" y=\"-53.4\" width=\"1.8\" height=\"18.8\" rx=\"0.9\" fill=\"@cuirH\" opacity=\"0.7\" stroke=\"none\"/><rect x=\"-1\" y=\"-53.4\" width=\"1.4\" height=\"18.8\" rx=\"0.7\" fill=\"@cuirO\" opacity=\"0.5\" stroke=\"none\"/><!-- bout haut arrondi (extremite du baton) --><ellipse cx=\"-2.6\" cy=\"-53.6\" rx=\"3\" ry=\"1.5\" fill=\"@cuirH\" stroke=\"#3a2410\" stroke-width=\"0.5\"/><!-- talon bas (ou la laniere se noue) --><ellipse cx=\"-2.6\" cy=\"-34.4\" rx=\"3\" ry=\"1.4\" fill=\"@cuirO\" stroke=\"#3a2410\" stroke-width=\"0.5\"/><!-- deux frettes de fer (anneaux de renfort, lisent le battant comme outil) --><rect x=\"-5.8\" y=\"-50\" width=\"6.4\" height=\"1.6\" rx=\"0.7\" fill=\"@metal\" stroke=\"none\"/><rect x=\"-5.8\" y=\"-39\" width=\"6.4\" height=\"1.6\" rx=\"0.7\" fill=\"@metal\" stroke=\"none\"/></g>",
  palette: {"metal":"#3a3038","cuirO":"#7a5226","cuir":"#c79356","cuirH":"#e0b87a"},
};
