import type { WeaponDef } from '../types';

export const weapon: WeaponDef = {
  slug: "pioche_2m",
  label: "Pioche à deux mains",
  type: "melee",
  group: "Deux-mains",
  target: "pic/pioche de guerre à deux mains, longue pointe courbe",
  art: "<!-- Pioche de guerre a deux mains, cand2 (v2) : LA POINTE est tout. Un seul long pic courbe tres effile sur une longue hampe. Repere os 'arme', poignee (0,0), tete vers -y. --><!-- talon / butt-cap sous la main (+y) --><rect x=\"-2.2\" y=\"5\" width=\"4.4\" height=\"3.6\" rx=\"1.2\" fill=\"@metalO\" stroke=\"@metalO\" stroke-width=\"0.5\"/><!-- LONGUE hampe en bois (deux mains) du poing (y=6) jusqu'a la tete (y=-39) --><rect x=\"-1.9\" y=\"-39\" width=\"3.8\" height=\"45\" rx=\"1.6\" fill=\"@cuir\" stroke=\"@cuirO\" stroke-width=\"0.5\"/><rect x=\"-1.4\" y=\"-38\" width=\"1.2\" height=\"43\" fill=\"@cuirH\" opacity=\"0.55\"/><!-- bagues de prise (deux mains marquees) --><g stroke=\"@cuirO\" stroke-width=\"0.6\" opacity=\"0.85\"><line x1=\"-1.9\" y1=\"-2\" x2=\"1.9\" y2=\"-1\"/><line x1=\"-1.9\" y1=\"2\" x2=\"1.9\" y2=\"3\"/><line x1=\"-1.9\" y1=\"-23\" x2=\"1.9\" y2=\"-22\"/></g><!-- collier / oeil d'acier emmanchant la tete sur la hampe --><rect x=\"-3\" y=\"-42\" width=\"6\" height=\"7.5\" rx=\"1.2\" fill=\"@metalO\" stroke=\"@metalO\" stroke-width=\"0.6\"/><circle cx=\"-1.6\" cy=\"-38.5\" r=\"0.7\" fill=\"@metalH\"/><circle cx=\"1.6\" cy=\"-38.5\" r=\"0.7\" fill=\"@metalH\"/><!-- petit contre-bec NET au dos (pas un poll de marteau) : juste assez pour signer le pic de guerre --><path d=\"M-2.8 -41 L-8.5 -43 L-9 -40.5 L-2.8 -38 Z\" fill=\"@metal\" stroke=\"@metalO\" stroke-width=\"0.6\" stroke-linejoin=\"round\"/><!-- ============ LA SIGNATURE ============ --><!-- UN seul long pic COURBE et tres EFFILE : part du collier, balaie haut puis vers l'avant (+x), file jusqu'a une pointe aceree en (16,-55). Racine large -> pointe fine. --><path d=\"M2.6 -37 Q3 -43 4.6 -47.5 Q6.6 -52 10 -54.8 Q13.4 -57 16 -55 Q12.8 -53 10.6 -50 Q8 -46 6 -42 Q4.6 -38.5 4 -36 Z\" fill=\"@metal\" stroke=\"@metalO\" stroke-width=\"0.75\" stroke-linejoin=\"round\"/><!-- arete vive / reflet le long du DOS du pic (haut) --><path d=\"M3.4 -36.5 Q4.8 -45 7.2 -49.5 Q10.2 -54 15.2 -55.2\" fill=\"none\" stroke=\"@metalH\" stroke-width=\"0.9\" stroke-opacity=\"0.9\" stroke-linecap=\"round\"/><!-- ombre du creux interieur (face de frappe sous le bec) --><path d=\"M3.2 -36 Q4.4 -41 5.8 -44.5 Q7.8 -49 10.8 -51.5\" fill=\"none\" stroke=\"@metalO\" stroke-width=\"0.6\" stroke-opacity=\"0.7\"/>",
  palette: {"metalO":"#2a3038","metalH":"#cfd8e6","metal":"#9aa6b8","cuir":"#5a3f24","cuirO":"#33241a","cuirH":"#7c5832"},
};
