// ⚠️ GÉNÉRÉ par scripts/gen-registry.mjs — NE PAS ÉDITER À LA MAIN.
// Ajouter une entrée = déposer un fichier dans defs/ puis `npm run gen`.
import type { IconFamily } from './types';
import { icons as e0 } from './defs/action';
import { icons as e1 } from './defs/char';
import { icons as e2 } from './defs/condition';
import { icons as e3 } from './defs/creature';
import { icons as e4 } from './defs/flag';
import { icons as e5 } from './defs/item';
import { icons as e6 } from './defs/journal';
import { icons as e7 } from './defs/nav';
import { icons as e8 } from './defs/resource';
import { icons as e9 } from './defs/scenario';
import { icons as e10 } from './defs/time';
import { icons as e11 } from './defs/travel';
import { icons as e12 } from './defs/ui';

export const ICON_FAMILIES: IconFamily[] = [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12];

/** Union GÉNÉRÉE des `id` déclarés dans les defs — le typage réel des consommateurs. */
export type IconIdGenerated =
  | 'action/aim'
  | 'action/attack'
  | 'action/break-free'
  | 'action/cast'
  | 'action/consume'
  | 'action/defend'
  | 'action/disengage'
  | 'action/dismount'
  | 'action/dispel'
  | 'action/free-attack'
  | 'action/lead'
  | 'action/leave-post'
  | 'action/mount'
  | 'action/pick-up'
  | 'action/roll-fire'
  | 'action/serve-engine'
  | 'action/shoot'
  | 'action/stand-up'
  | 'action/steer-ship'
  | 'char/ag'
  | 'char/cc'
  | 'char/ct'
  | 'char/e'
  | 'char/f'
  | 'char/fm'
  | 'char/int'
  | 'char/soc'
  | 'condition/ablaze'
  | 'condition/bleeding'
  | 'condition/blinded'
  | 'condition/broken'
  | 'condition/deafened'
  | 'condition/entangled'
  | 'condition/fatigued'
  | 'condition/petrified'
  | 'condition/poisoned'
  | 'condition/prone'
  | 'condition/stunned'
  | 'condition/surprised'
  | 'condition/unconscious'
  | 'creature/bite'
  | 'creature/breath'
  | 'creature/gaze'
  | 'creature/horns'
  | 'creature/scream'
  | 'creature/squeeze'
  | 'creature/tail'
  | 'creature/tentacles'
  | 'creature/tongue'
  | 'creature/vomit'
  | 'flag/defensive'
  | 'flag/fear'
  | 'flag/focus'
  | 'flag/frenzy'
  | 'flag/hungry'
  | 'item/ammo'
  | 'item/armour'
  | 'item/cloak'
  | 'item/consumable'
  | 'item/misc'
  | 'item/weapon'
  | 'journal/charge'
  | 'journal/critical'
  | 'journal/damage'
  | 'journal/death'
  | 'journal/detail'
  | 'journal/dodge'
  | 'journal/flee'
  | 'journal/heal'
  | 'journal/info'
  | 'journal/move'
  | 'journal/reload'
  | 'journal/round'
  | 'nav/activity'
  | 'nav/art-gallery'
  | 'nav/campaign'
  | 'nav/compendium'
  | 'nav/dice'
  | 'nav/editor'
  | 'nav/entry-point'
  | 'nav/identify'
  | 'nav/load'
  | 'nav/memorize'
  | 'nav/mutation'
  | 'nav/new-game'
  | 'nav/online'
  | 'nav/rest'
  | 'nav/rules'
  | 'nav/seat-owner'
  | 'nav/test-scenarios'
  | 'resource/fate'
  | 'resource/fortune'
  | 'resource/gold-purse'
  | 'resource/movement'
  | 'resource/resilience'
  | 'resource/resolve'
  | 'resource/wounds'
  | 'scenario/ambush'
  | 'scenario/arena'
  | 'scenario/bestiary'
  | 'scenario/bridge'
  | 'scenario/gallery'
  | 'scenario/hamlet'
  | 'scenario/magic'
  | 'scenario/magic-field'
  | 'scenario/market'
  | 'scenario/naval'
  | 'scenario/opera'
  | 'scenario/port'
  | 'scenario/siege'
  | 'scenario/training'
  | 'scenario/trap'
  | 'scenario/travel'
  | 'scenario/village'
  | 'time/afternoon'
  | 'time/dawn'
  | 'time/dusk'
  | 'time/evening'
  | 'time/morning'
  | 'time/night'
  | 'time/noon'
  | 'travel/anchor'
  | 'travel/barge'
  | 'travel/cart'
  | 'travel/coach'
  | 'travel/foot'
  | 'travel/mount'
  | 'travel/rowboat'
  | 'travel/sail-ship'
  | 'ui/done'
  | 'ui/preempt'
  | 'ui/round-start'
  | 'ui/turn-end'
  | 'ui/undo'
  | 'ui/wait'
  | 'ui/warning';
